import { BadRequestException, Injectable } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../database/prisma.service.js';

const DAY = 86_400_000;
const numeric = (value: unknown) => Number(value ?? 0);
const iso = (value: unknown) => value instanceof Date ? value.toISOString() : String(value);

@Injectable()
export class AnalyticsService {
  constructor(private readonly prisma: PrismaService) {}
  private window(range = '30d') { const now = new Date(); let start: Date; let end = now; if (range === 'today') { start = new Date(now); start.setHours(0, 0, 0, 0); } else if (range === '7d') start = new Date(now.getTime() - 7 * DAY); else if (range === 'year') start = new Date(now.getFullYear(), 0, 1); else if (range === 'month') start = new Date(now.getFullYear(), now.getMonth(), 1); else if (range === 'last-month') { start = new Date(now.getFullYear(), now.getMonth() - 1, 1); end = new Date(now.getFullYear(), now.getMonth(), 1); } else if (range === '30d') start = new Date(now.getTime() - 30 * DAY); else throw new BadRequestException('Invalid analytics range'); return { start, end, previousStart: new Date(start.getTime() - (end.getTime() - start.getTime())), previousEnd: start, bucket: (end.getTime() - start.getTime()) > 120 * DAY ? 'month' : (end.getTime() - start.getTime()) > 31 * DAY ? 'week' : 'day' }; }
  async getDashboard(range = '30d') { const window = this.window(range); const previous = await this.summary(window.previousStart, window.previousEnd); const current = await this.summary(window.start, window.end); const [trend, statuses, orderStatuses, orders, payments, users, topItems, service, serviceTrend, serviceRecent] = await Promise.all([this.trend(window), this.statuses(window.start, window.end), this.orderStatuses(window.start, window.end), this.recentOrders(), this.recentPayments(), this.recentUsers(), this.topItems(window.start, window.end), this.serviceSummary(window.start, window.end), this.serviceTrend(window), this.recentServiceBookings()]); const compare = (key: keyof typeof current) => ({ value: current[key], previous: previous[key], change: previous[key] ? Number((((current[key] - previous[key]) / previous[key]) * 100).toFixed(1)) : current[key] ? 100 : 0 }); const productOrders = { summary: current, status: statuses.map((row) => ({ status: row.status, count: numeric(row.count), amount: numeric(row.amount) })), orderStatus: orderStatuses.map((row) => ({ status: row.status, count: numeric(row.count) })), trend: trend.map((row) => ({ label: iso(row.label), revenue: numeric(row.revenue), orders: numeric(row.orders) })), recent: orders }; return { range: { start: window.start, end: window.end, bucket: window.bucket }, summary: current, comparison: { revenue: compare('revenue'), orders: compare('orders'), successfulPayments: compare('successfulPayments'), customers: compare('customers'), trainers: compare('trainers') }, revenueTrend: productOrders.trend, paymentStatus: productOrders.status, recentOrders: orders, recentPayments: payments, recentUsers: users, topItems, productOrders, serviceBookings: { summary: service, trend: serviceTrend.map((row) => ({ label: iso(row.label), revenue: numeric(row.revenue), bookings: numeric(row.bookings) })), recent: serviceRecent } }; }
  private async summary(start: Date, end: Date) { const productWhere = { items: { some: { type: 'PRODUCT' as const }, none: { type: 'SERVICE' as const } } }; const [orders, payments, customers, trainers, revenue] = await Promise.all([this.prisma.order.count({ where: { ...productWhere, createdAt: { gte: start, lt: end } } }), this.prisma.payment.count({ where: { status: 'PAID', createdAt: { gte: start, lt: end }, order: productWhere } }), this.prisma.user.count({ where: { role: 'USER', createdAt: { gte: start, lt: end } } }), this.prisma.user.count({ where: { role: 'TRAINER', createdAt: { gte: start, lt: end } } }), this.prisma.order.aggregate({ _sum: { total: true }, where: { ...productWhere, createdAt: { gte: start, lt: end }, payment: { status: 'PAID' } } })]); return { revenue: numeric(revenue._sum.total), orders, successfulPayments: payments, customers, trainers }; }
  private async trend(window: { start: Date; end: Date; bucket: string }) { const unit = Prisma.raw(`'${window.bucket}'`); return this.prisma.$queryRaw<Array<{ label: Date; revenue: Prisma.Decimal; orders: bigint }>>(Prisma.sql`SELECT DATE_TRUNC(${unit}, o."createdAt") label, COALESCE(SUM(CASE WHEN p.status = 'PAID' THEN o.total ELSE 0 END), 0) revenue, COUNT(*) orders FROM "Order" o LEFT JOIN "Payment" p ON p."orderId" = o.id WHERE o."createdAt" >= ${window.start} AND o."createdAt" < ${window.end} AND EXISTS (SELECT 1 FROM "OrderItem" oi WHERE oi."orderId" = o.id AND oi.type = 'PRODUCT') AND NOT EXISTS (SELECT 1 FROM "OrderItem" si WHERE si."orderId" = o.id AND si.type = 'SERVICE') GROUP BY DATE_TRUNC(${unit}, o."createdAt") ORDER BY label`); }
  private async statuses(start: Date, end: Date) { const rows = await this.prisma.payment.groupBy({ by: ['status'], _count: { _all: true }, _sum: { amount: true }, where: { createdAt: { gte: start, lt: end }, order: { items: { some: { type: 'PRODUCT' }, none: { type: 'SERVICE' } } } } }); return rows.map((row) => ({ status: row.status, count: typeof row._count === 'object' ? row._count?._all ?? 0 : 0, amount: numeric(row._sum?.amount) })).sort((a, b) => b.count - a.count); }
  private async orderStatuses(start: Date, end: Date) { const rows = await this.prisma.order.groupBy({ by: ['status'], _count: { _all: true }, where: { createdAt: { gte: start, lt: end }, items: { some: { type: 'PRODUCT' }, none: { type: 'SERVICE' } } } }); return rows.map((row) => ({ status: row.status, count: row._count._all })).sort((a, b) => b.count - a.count); }
  private async recentOrders() { return this.prisma.order.findMany({ where: { items: { some: { type: 'PRODUCT' }, none: { type: 'SERVICE' } } }, take: 8, orderBy: { createdAt: 'desc' }, select: { id: true, name: true, email: true, total: true, status: true, createdAt: true, items: { select: { id: true } }, payment: { select: { status: true } } } }).then((rows) => rows.map((row) => ({ id: row.id, customer: row.name, email: row.email, total: numeric(row.total), status: row.status, paymentStatus: row.payment?.status ?? 'PENDING', createdAt: row.createdAt, items: row.items.length }))); }
  private async serviceSummary(start: Date, end: Date) { const where = { createdAt: { gte: start, lt: end } }; const [total, pending, scheduled, completed, cancelled, revenue] = await Promise.all([this.prisma.serviceBooking.count({ where }), this.prisma.serviceBooking.count({ where: { ...where, status: { in: ['PENDING_PAYMENT', 'PENDING'] } } }), this.prisma.serviceBooking.count({ where: { ...where, status: { in: ['CONFIRMED', 'SCHEDULED'] } } }), this.prisma.serviceBooking.count({ where: { ...where, status: 'COMPLETED' } }), this.prisma.serviceBooking.count({ where: { ...where, status: 'CANCELLED' } }), this.prisma.serviceBooking.aggregate({ _sum: { totalAmount: true }, where: { ...where, order: { payment: { status: 'PAID' } } } })]); const upcoming = await this.prisma.serviceSession.count({ where: { scheduledAt: { gte: new Date() }, status: { not: 'CANCELLED' }, booking: { createdAt: { gte: start, lt: end }, status: { not: 'CANCELLED' } } } }); return { total, pending, confirmed: scheduled, upcoming, completed, cancelled, revenue: numeric(revenue._sum.totalAmount) }; }
  private async serviceTrend(window: { start: Date; end: Date; bucket: string }) { const unit = Prisma.raw(`'${window.bucket}'`); return this.prisma.$queryRaw<Array<{ label: Date; revenue: Prisma.Decimal; bookings: bigint }>>(Prisma.sql`SELECT DATE_TRUNC(${unit}, sb."createdAt") label, COALESCE(SUM(CASE WHEN p.status = 'PAID' THEN sb."totalAmount" ELSE 0 END), 0) revenue, COUNT(*) bookings FROM "ServiceBooking" sb JOIN "Order" o ON o.id = sb."orderId" LEFT JOIN "Payment" p ON p."orderId" = o.id WHERE sb."createdAt" >= ${window.start} AND sb."createdAt" < ${window.end} GROUP BY DATE_TRUNC(${unit}, sb."createdAt") ORDER BY label`); }
  private async recentServiceBookings() { return this.prisma.serviceBooking.findMany({ take: 8, orderBy: { createdAt: 'desc' }, include: { service: { select: { name: true } }, trainer: { select: { name: true } }, sessions: { orderBy: { scheduledAt: 'asc' }, take: 1 }, order: { select: { name: true, payment: { select: { status: true } } } } } }).then((rows) => rows.map((row) => ({ id: row.id, customer: row.order.name, service: row.service.name, trainer: row.trainer.name, session: row.sessions[0]?.scheduledAt ?? null, quantity: row.quantity, total: numeric(row.totalAmount), status: row.status, paymentStatus: row.order.payment?.status ?? 'PENDING', createdAt: row.createdAt }))); }
  private async recentPayments() { return this.prisma.payment.findMany({ take: 8, orderBy: { createdAt: 'desc' }, select: { id: true, orderId: true, status: true, amount: true, currency: true, paymentMethod: true, razorpayPaymentId: true, createdAt: true, order: { select: { name: true, email: true } } } }).then((rows) => rows.map((row) => ({ id: row.id, orderId: row.orderId, status: row.status, amount: numeric(row.amount), currency: row.currency, paymentMethod: row.paymentMethod, razorpayPaymentId: row.razorpayPaymentId, createdAt: row.createdAt, customer: row.order.name, email: row.order.email }))); }
  private async recentUsers() { return this.prisma.user.findMany({ where: { role: 'USER' }, take: 8, orderBy: { createdAt: 'desc' }, select: { id: true, name: true, email: true, role: true, createdAt: true } }); }
  private async topItems(start: Date, end: Date) { return this.prisma.orderItem.groupBy({ by: ['type', 'name'], _sum: { quantity: true, total: true }, where: { type: 'PRODUCT', order: { createdAt: { gte: start, lt: end }, payment: { status: 'PAID' } } }, orderBy: { _sum: { quantity: 'desc' } }, take: 6 }).then((rows) => rows.map((row) => ({ type: row.type, name: row.name, units: row._sum.quantity ?? 0, revenue: numeric(row._sum.total) }))); }
}
