import { EditIcon, TrashIcon } from "@/components/ui/icons";
import type { Category } from "@/types/category";

function date(value: string) { return new Intl.DateTimeFormat("en-US", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T00:00:00`)); }

export function CategoryTable({ categories, onDelete, onEdit }: { categories: Category[]; onDelete: (category: Category) => void; onEdit: (category: Category) => void }) {
  if (!categories.length) return <div className="px-6 py-20 text-center"><p className="font-serif text-2xl">No categories found</p><p className="mt-2 text-sm text-brand-gray">Try adjusting your search.</p></div>;
  return <div className="overflow-x-auto"><table className="w-full min-w-[820px] border-collapse text-left"><thead><tr className="border-b border-black/10 text-[10px] font-semibold uppercase tracking-[0.16em] text-brand-gray"><th className="px-6 py-4">Category</th><th className="px-6 py-4">Description</th><th className="px-6 py-4">Products</th><th className="px-6 py-4">Created</th><th className="px-6 py-4 text-right">Actions</th></tr></thead><tbody>{categories.map((category) => <tr className="border-b border-black/5 transition-colors last:border-0 hover:bg-brand-light-gray/70" key={category.id}><td className="px-6 py-5"><div className="flex items-center gap-3"><div className="relative h-12 w-12 shrink-0 overflow-hidden rounded-md bg-brand-light-gray"><Image alt={category.name} className="object-cover" fill sizes="48px" src={category.image} /></div><span className="text-sm font-semibold">{category.name}</span></div></td><td className="max-w-[310px] truncate px-6 py-5 text-sm text-brand-gray">{category.description}</td><td className="px-6 py-5 text-sm text-brand-gray">{category.productCount}</td><td className="whitespace-nowrap px-6 py-5 text-sm text-brand-gray">{date(category.createdAt)}</td><td className="px-6 py-5"><div className="flex justify-end gap-2"><button aria-label={`Edit ${category.name}`} className="inline-flex h-9 w-9 items-center justify-center rounded-md text-brand-gray transition-colors hover:bg-brand-purple/10 hover:text-brand-purple" onClick={() => onEdit(category)} type="button"><EditIcon /></button><button aria-label={`Delete ${category.name}`} className="inline-flex h-9 w-9 items-center justify-center rounded-md text-brand-gray transition-colors hover:bg-red-50 hover:text-red-600" onClick={() => onDelete(category)} type="button"><TrashIcon /></button></div></td></tr>)}</tbody></table></div>;
}
import Image from "next/image";
