ALTER TABLE "ServiceBooking" ADD COLUMN IF NOT EXISTS "otpEncrypted" TEXT;
ALTER TABLE "ServiceBooking" ADD COLUMN IF NOT EXISTS "otpAttempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ServiceBooking" ADD COLUMN IF NOT EXISTS "otpBlockedUntil" TIMESTAMP(3);
ALTER TABLE "ServiceBooking" ADD COLUMN IF NOT EXISTS "verifiedBy" TEXT;
