type EmailOrder = any;
const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' } as Record<string, string>)[character] ?? character);
const money = (value: unknown) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(value ?? 0));
const statusLabel = (value: string) => value.replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const address = (order: EmailOrder) => [order.name, order.address, order.city, order.state, order.postalCode, order.country, order.phone].filter(Boolean).map(escape).join('<br>');
const itemRows = (order: EmailOrder) => order.items.filter((item: any) => item.type === 'PRODUCT').map((item: any) => `<tr><td style="padding:12px 8px;border-bottom:1px solid #eee">${item.image ? `<img src="${escape(item.image)}" alt="" width="48" height="48" style="display:inline-block;vertical-align:middle;object-fit:cover;margin-right:8px">` : ''}${escape(item.name)}</td><td style="padding:12px 8px;border-bottom:1px solid #eee;text-align:center">${item.quantity}</td><td style="padding:12px 8px;border-bottom:1px solid #eee;text-align:right">${money(item.price)}</td><td style="padding:12px 8px;border-bottom:1px solid #eee;text-align:right">${money(item.total)}</td></tr>`).join('');
const summary = (order: EmailOrder) => { const subtotal = Number(order.subtotal ?? 0); const couponDiscount = Number(order.couponDiscountAmount ?? 0); const shipping = Number(order.shippingCharge ?? 0); const total = subtotal - couponDiscount + shipping; const shippingLabel = shipping === 0 ? 'Shipping included in cost' : money(shipping); return `<table style="width:100%;border-collapse:collapse;margin-top:18px"><tr><td>Subtotal</td><td style="text-align:right">${money(subtotal)}</td></tr>${order.couponCode && couponDiscount > 0 ? `<tr><td>Coupon discount (${escape(order.couponCode)})</td><td style="text-align:right;color:#16803c">-${money(couponDiscount)}</td></tr>` : ''}<tr><td>Shipping</td><td style="text-align:right">${shippingLabel}</td></tr><tr><td style="padding-top:12px;font-weight:bold;font-size:18px">Total</td><td style="padding-top:12px;text-align:right;font-weight:bold;font-size:18px">${money(total)}</td></tr></table>`; };
const layout = (title: string, content: string) => `<!doctype html><html><body style="margin:0;background:#f7f5f1;color:#282421;font-family:Arial,sans-serif"><div style="max-width:680px;margin:24px auto;background:#fff;padding:32px"><div style="border-bottom:2px solid #6c4a86;padding-bottom:18px;color:#6c4a86;font-size:24px;font-weight:bold">Yoga Fitness</div><h1 style="font-size:26px;font-weight:normal">${title}</h1>${content}<p style="border-top:1px solid #eee;margin-top:32px;padding-top:18px;color:#777;font-size:12px">© Yoga Fitness</p></div></body></html>`;
const base = (order: EmailOrder, url: string, extra = '') => `<p>Hello ${escape(order.name)},</p>${extra}<p><b>Order #${escape(order.id.slice(0, 8))}</b><br>Placed ${new Date(order.createdAt).toLocaleString('en-US')}<br>Status: <b>${escape(statusLabel(order.status))}</b></p><table style="width:100%;border-collapse:collapse;font-size:14px"><thead><tr style="background:#f7f5f1"><th style="padding:10px 8px;text-align:left">Product</th><th style="padding:10px 8px">Qty</th><th style="padding:10px 8px;text-align:right">Unit price</th><th style="padding:10px 8px;text-align:right">Total</th></tr></thead><tbody>${itemRows(order)}</tbody></table>${summary(order)}<h3 style="margin-top:28px">Shipping address</h3><p style="line-height:1.7">${address(order)}</p><p>Payment: ${escape(order.payment?.paymentMethod ?? 'Not yet paid')}<br>Payment status: ${escape(order.payment?.status ?? 'PENDING')}</p><p style="margin-top:26px;text-align:center"><a href="${escape(url)}" style="display:inline-block;background:#6c4a86;color:#fff;padding:13px 22px;text-decoration:none">Track order</a></p>`;
const statusCopy: Record<string, string> = { confirmed: 'Your order has been confirmed.', processing: 'Your order is being processed.', shipped: 'Your order has been shipped.', out_for_delivery: 'Your order is out for delivery.', delivered: 'Your order has been delivered.', cancelled: 'Your order has been cancelled.', refunded: 'Your order has been refunded.' };
const statusSubjects: Record<string, string> = { confirmed: 'Has Been Confirmed', processing: 'Is Being Processed', shipped: 'Has Been Shipped', out_for_delivery: 'Is Out for Delivery', delivered: 'Has Been Delivered', cancelled: 'Has Been Cancelled', refunded: 'Has Been Refunded' };
const emailTotal = (order: EmailOrder) => Number(order.subtotal ?? 0) - Number(order.couponDiscountAmount ?? 0) + Number(order.shippingCharge ?? 0);
export function confirmation(order: EmailOrder, url: string) { return { subject: `Order Confirmation #${order.id.slice(0, 8)}`, html: layout('Thank you for your order', base(order, url, '<p>We have received your product order and will keep you updated.</p>')), text: `Thank you for your order #${order.id}. Status: ${order.status}. Total: ${money(emailTotal(order))}. View: ${url}` }; }
export function adminNewOrder(order: EmailOrder, url: string) { return { subject: `New product order #${order.id.slice(0, 8)}`, html: layout('New product order', `<p>Customer: ${escape(order.name)} (${escape(order.email)})${order.phone ? ` · ${escape(order.phone)}` : ''}</p>${base(order, url)}`), text: `New order #${order.id} from ${order.name} (${order.email}). Total: ${money(emailTotal(order))}. View: ${url}` }; }
export function statusUpdate(order: EmailOrder, oldStatus: string, url: string) { const label = statusLabel(order.status); return { subject: `Your Order #${order.id.slice(0, 8)} ${statusSubjects[order.status] ?? `Status Is Now ${label}`}`, html: layout(`Order ${label}`, base(order, url, `<p>${escape(statusCopy[order.status] ?? `Your order status is now ${label}.`)}${oldStatus ? ` Previous status: ${escape(statusLabel(oldStatus))}.` : ''}</p>`)), text: `Order #${order.id} status changed from ${oldStatus} to ${order.status}. View: ${url}` }; }
