type Booking = any;

const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' } as Record<string, string>)[character] ?? character);
const money = (value: unknown) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(value ?? 0));
const label = (value: unknown) => String(value ?? '').replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const date = (value: unknown) => value ? new Intl.DateTimeFormat('en-US', { dateStyle: 'long' }).format(new Date(String(value))) : '';
const time = (value: unknown) => value ? new Intl.DateTimeFormat('en-US', { timeStyle: 'short', timeZone: 'UTC' }).format(new Date(String(value))) : '';
const sessions = (booking: Booking) => (booking.sessions ?? []).map((session: any, index: number) => `<tr><td style="padding:10px 8px;border-bottom:1px solid #eee">Session ${index + 1}</td><td style="padding:10px 8px;border-bottom:1px solid #eee">${escape(date(session.scheduledAt))}</td><td style="padding:10px 8px;border-bottom:1px solid #eee">${escape(time(session.scheduledAt))}</td><td style="padding:10px 8px;border-bottom:1px solid #eee;text-align:right">${escape(label(session.status))}</td></tr>`).join('');
const layout = (title: string, content: string) => `<!doctype html><html><body style="margin:0;background:#f7f5f1;color:#282421;font-family:Arial,sans-serif"><div style="max-width:680px;margin:24px auto;background:#fff;padding:32px"><div style="border-bottom:2px solid #6c4a86;padding-bottom:18px;color:#6c4a86;font-size:24px;font-weight:bold">Yoga Fitness</div><h1 style="font-size:26px;font-weight:normal">${escape(title)}</h1>${content}<p style="border-top:1px solid #eee;margin-top:32px;padding-top:18px;color:#777;font-size:12px">© Yoga Fitness</p></div></body></html>`;
const bookingInfo = (booking: Booking, includePayment = true) => `<table style="width:100%;border-collapse:collapse;font-size:14px"><tr><td style="padding:7px 0;color:#777">Booking</td><td style="padding:7px 0;text-align:right;font-weight:bold">#${escape(booking.id.slice(0, 8))}</td></tr><tr><td style="padding:7px 0;color:#777">Service</td><td style="padding:7px 0;text-align:right">${escape(booking.service?.name)}</td></tr>${booking.trainer ? `<tr><td style="padding:7px 0;color:#777">Trainer</td><td style="padding:7px 0;text-align:right">${escape(booking.trainer.name)}</td></tr>` : ''}<tr><td style="padding:7px 0;color:#777">Sessions</td><td style="padding:7px 0;text-align:right">${booking.quantity}</td></tr><tr><td style="padding:7px 0;color:#777">Booking status</td><td style="padding:7px 0;text-align:right">${escape(label(booking.status))}</td></tr>${includePayment ? `<tr><td style="padding:7px 0;color:#777">Payment</td><td style="padding:7px 0;text-align:right">${escape(booking.order?.payment?.paymentMethod ?? 'Not yet paid')} · ${escape(label(booking.order?.payment?.status ?? 'PENDING'))}</td></tr><tr><td style="padding:7px 0;color:#777">Total</td><td style="padding:7px 0;text-align:right;font-weight:bold">${money(booking.totalAmount)}</td></tr>` : ''}</table><h3 style="margin:26px 0 8px">Scheduled sessions</h3><table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr style="background:#f7f5f1"><th style="padding:10px 8px;text-align:left">Session</th><th style="padding:10px 8px;text-align:left">Date</th><th style="padding:10px 8px;text-align:left">Time</th><th style="padding:10px 8px;text-align:right">Status</th></tr></thead><tbody>${sessions(booking)}</tbody></table>`;
const cta = (url: string, text = 'View Booking') => `<p style="margin-top:26px"><a href="${escape(url)}" style="display:inline-block;background:#6c4a86;color:#fff;padding:13px 22px;text-decoration:none">${escape(text)}</a></p>`;
const customer = (booking: Booking) => `<p>Hello ${escape(booking.order?.name)},</p>`;
const address = (booking: Booking) => [booking.address, booking.city, booking.state, booking.postalCode, booking.country].filter(Boolean).map(escape).join('<br>');

export function bookingConfirmationCustomer(booking: Booking, otp: string, url: string) {
  return { subject: `Your ${booking.service?.name ?? 'Service'} Booking Confirmation`, html: layout('Booking confirmed', `${customer(booking)}<p>Your booking has been created successfully. Please provide the following OTP to your assigned trainer at the time of your session.</p><div style="margin:24px 0;padding:20px;text-align:center;background:#f7f5f1"><p style="margin:0;color:#777">Your Session OTP</p><p style="margin:8px 0 0;font-size:30px;font-weight:bold;letter-spacing:5px">${escape(otp)}</p></div><p><b>Do not share this OTP with anyone other than your assigned trainer.</b></p>${bookingInfo(booking)}<p>Address:<br>${address(booking)}</p>${cta(url, 'View My Booking')}`), text: `Your ${booking.service?.name ?? 'service'} booking is confirmed. Booking #${booking.id}. Your session OTP is ${otp}. Share it only with your assigned trainer. View booking: ${url}` };
}

export function bookingNewAdmin(booking: Booking, url: string) {
  return { subject: `New Service Booking #${booking.id.slice(0, 8)}`, html: layout('New service booking', `<p>Customer: <b>${escape(booking.order?.name)}</b><br>Email: ${escape(booking.order?.email)}${booking.order?.phone ? `<br>Phone: ${escape(booking.order.phone)}` : ''}</p>${bookingInfo(booking)}${cta(url)}`), text: `New service booking #${booking.id} from ${booking.order?.name} (${booking.order?.email}). View booking: ${url}` };
}

export function sessionConfirmedCustomer(booking: Booking, confirmedAt: Date, url: string) {
  return { subject: `Your ${booking.service?.name ?? 'Yoga'} Session Has Been Confirmed`, html: layout('Your session has been confirmed', `${customer(booking)}<p>Your session has been completed and confirmed by your trainer.</p>${bookingInfo(booking, false)}<p>Confirmation time: ${escape(new Date(confirmedAt).toLocaleString('en-US'))}</p>${cta(url, 'View My Booking')}`), text: `Your session for booking #${booking.id} has been completed and confirmed by your trainer. View booking: ${url}` };
}

export function sessionConfirmedAdmin(booking: Booking, confirmedAt: Date, url: string) {
  return { subject: `Session Confirmed by Trainer — Booking #${booking.id.slice(0, 8)}`, html: layout('Trainer confirmation', `<p><b>Session Confirmed</b></p><p>Trainer: ${escape(booking.trainer?.name)}<br>Customer: ${escape(booking.order?.name)} (${escape(booking.order?.email)})${booking.order?.phone ? `<br>Phone: ${escape(booking.order.phone)}` : ''}<br>Service: ${escape(booking.service?.name)}<br>Confirmation time: ${escape(new Date(confirmedAt).toLocaleString('en-US'))}<br>Confirmation method: Trainer OTP Confirmation</p>${bookingInfo(booking, false)}${cta(url)}`), text: `Trainer ${booking.trainer?.name} confirmed the session for ${booking.order?.name}, booking #${booking.id}, using trainer OTP confirmation. View booking: ${url}` };
}

export function sessionReviewedCustomer(booking: Booking, decision: string, reviewedAt: Date, reason: string | undefined, url: string) {
  const approved = decision === 'APPROVED';
  return { subject: `Your ${booking.service?.name ?? 'Yoga'} Session Has Been ${approved ? 'Approved' : 'Reviewed'}`, html: layout(approved ? 'Your session has been reviewed and confirmed' : 'Your session review is complete', `${customer(booking)}<p>Your session has been reviewed by the administrator and is <b>${approved ? 'confirmed' : 'not approved'}</b>.</p>${bookingInfo(booking, false)}<p>Review status: ${escape(label(decision))}<br>Review time: ${escape(new Date(reviewedAt).toLocaleString('en-US'))}${reason ? `<br>Note: ${escape(reason)}` : ''}</p>${cta(url, 'View My Booking')}`), text: `Your session review for booking #${booking.id} is ${decision}. ${reason ?? ''} View booking: ${url}` };
}
