import Image from "next/image";

import { EditIcon, TrashIcon } from "@/components/ui/icons";
import type { Product } from "@/types/admin-product";

import { ProductAvailabilityToggle } from "./product-availability-toggle";
import { ProductStatusBadge } from "./product-status-badge";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
function stockLabel(stock: number) { return stock === 0 ? "Out of Stock" : stock <= 10 ? "Low Stock" : "In Stock"; }

export function ProductTable({ products, onDelete, onEdit, onToggleAvailability }: { products: Product[]; onDelete: (product: Product) => void; onEdit: (product: Product) => void; onToggleAvailability: (product: Product) => void }) {
  if (!products.length) return <div className="px-6 py-20 text-center"><p className="font-serif text-2xl">No products found</p><p className="mt-2 text-sm text-brand-gray">Try adjusting your search or filters.</p></div>;
  return <div className="overflow-x-auto"><table className="w-full min-w-[1180px] border-collapse text-left"><thead><tr className="border-b border-black/10 text-[10px] font-semibold uppercase tracking-[0.16em] text-brand-gray"><th className="px-6 py-4">Product</th><th className="px-6 py-4">Category</th><th className="px-6 py-4">Tags</th><th className="px-6 py-4">Price</th><th className="px-6 py-4">Stock</th><th className="px-6 py-4">Status</th><th className="px-6 py-4">Availability</th><th className="px-6 py-4 text-right">Actions</th></tr></thead><tbody>{products.map((product) => <tr className="border-b border-black/5 transition-colors last:border-0 hover:bg-brand-light-gray/70" key={product.id}><td className="px-6 py-4"><div className="flex items-center gap-3"><div className="relative h-12 w-12 shrink-0 overflow-hidden rounded-md bg-brand-light-gray"><Image alt={product.name} className="object-cover" fill sizes="48px" src={product.image} unoptimized /></div><span className="max-w-[210px] truncate text-sm font-semibold">{product.name}</span></div></td><td className="px-6 py-4 text-sm text-brand-gray">{product.categoryName}</td><td className="max-w-[210px] px-6 py-4"><div className="flex flex-wrap gap-1.5">{product.tags.slice(0, 3).map((tag) => <span className="rounded-full bg-brand-purple/10 px-2.5 py-1 text-[10px] text-brand-purple" key={tag}>{tag}</span>)}{product.tags.length > 3 && <span className="text-xs text-brand-gray">+{product.tags.length - 3}</span>}</div></td><td className="whitespace-nowrap px-6 py-4 text-sm font-semibold">{money.format(product.price)}</td><td className="px-6 py-4 text-sm text-brand-gray">{product.stock} <span className="block text-[10px]">{stockLabel(product.stock)}</span></td><td className="px-6 py-4"><ProductStatusBadge availability={product.availability} /></td><td className="px-6 py-4"><ProductAvailabilityToggle onChange={() => onToggleAvailability(product)} value={product.availability} /></td><td className="px-6 py-4"><div className="flex justify-end gap-2"><button aria-label={`Edit ${product.name}`} className="inline-flex h-9 w-9 items-center justify-center rounded-md text-brand-gray hover:bg-brand-purple/10 hover:text-brand-purple" onClick={() => onEdit(product)} type="button"><EditIcon /></button><button aria-label={`Delete ${product.name}`} className="inline-flex h-9 w-9 items-center justify-center rounded-md text-brand-gray hover:bg-red-50 hover:text-red-600" onClick={() => onDelete(product)} type="button"><TrashIcon /></button></div></td></tr>)}</tbody></table></div>;
}
