"use client";
import { useEffect, useMemo, useState } from "react";
import { getCategories } from "@/api/categories.api";
import { createProduct, deleteProduct as deleteProductRequest, getProducts, updateProduct, updateProductAvailability } from "@/api/products.api";
import { CustomerPagination } from "@/components/admin/customers/customer-pagination";
import { CustomerSearch } from "@/components/admin/customers/customer-search";
import { Button } from "@/components/ui/button";
import { Container } from "@/components/ui/container";
import type { Category } from "@/types/category";
import type { Product } from "@/types/admin-product";
import { DeleteProductDialog } from "./delete-product-dialog";
import { ProductFormModal } from "./product-form-modal";
import { ProductTable } from "./product-table";
const PAGE_SIZE = 10;
export function ProductsPage() {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [query, setQuery] = useState(""); const [debouncedQuery, setDebouncedQuery] = useState(""); const [categoryFilter, setCategoryFilter] = useState("All"); const [availabilityFilter, setAvailabilityFilter] = useState("All"); const [page, setPage] = useState(1); const [editing, setEditing] = useState<Product>(); const [deleting, setDeleting] = useState<Product>(); const [modalOpen, setModalOpen] = useState(false); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(""); const [feedback, setFeedback] = useState("");
  useEffect(() => { Promise.allSettled([getProducts(), getCategories()]).then(([productResult, categoryResult]) => { if (productResult.status === "fulfilled") setProducts(productResult.value); else setError(productResult.reason instanceof Error ? productResult.reason.message : "Unable to load products."); if (categoryResult.status === "fulfilled") setCategories(categoryResult.value); else setError(categoryResult.reason instanceof Error ? categoryResult.reason.message : "Unable to load categories."); }).finally(() => setLoading(false)); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { setDebouncedQuery(query.trim().toLowerCase()); setPage(1); }, 400); return () => window.clearTimeout(timer); }, [query]);
  const filtered = useMemo(() => products.filter((product) => (!debouncedQuery || `${product.name} ${product.categoryName} ${product.id}`.toLowerCase().includes(debouncedQuery)) && (categoryFilter === "All" || product.categoryId === categoryFilter) && (availabilityFilter === "All" || product.availability === availabilityFilter)), [products, debouncedQuery, categoryFilter, availabilityFilter]); const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  async function save(product: Product) { try { setSubmitting(true); setError(""); const data = { name: product.name, description: product.description, price: product.price, categoryId: product.categoryId, tags: product.tags, imageUrl: product.image, stock: product.stock, available: product.availability === "Available" }; const saved = editing ? await updateProduct(product.id, data) : await createProduct(data); setProducts((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [saved, ...current]); setModalOpen(false); setEditing(undefined); setFeedback(editing ? "Product updated successfully." : "Product created successfully."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save product."); } finally { setSubmitting(false); } }
  async function remove() { if (!deleting) return; try { setSubmitting(true); await deleteProductRequest(deleting.id); setProducts((current) => current.filter((item) => item.id !== deleting.id)); setDeleting(undefined); setFeedback("Product deleted successfully."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to delete product."); } finally { setSubmitting(false); } }
  async function toggle(product: Product) { try { setSubmitting(true); const saved = await updateProductAvailability(product.id, product.availability !== "Available"); setProducts((current) => current.map((item) => item.id === saved.id ? saved : item)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update availability."); } finally { setSubmitting(false); } }
  const selectClass = "h-12 rounded-md border border-black/10 bg-white px-4 text-sm outline-none focus:border-brand-purple";
  return <Container className="py-10 sm:py-12 lg:py-16"><div className="flex flex-col gap-7 border-b border-black/10 pb-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-brand-purple">Sattva administration</p><h1 className="mt-3 text-4xl sm:text-5xl">Products</h1><p className="mt-3 text-sm text-brand-gray">Manage your yoga and wellness catalog.</p></div><Button disabled={submitting || loading} onClick={() => { setEditing(undefined); setModalOpen(true); }} type="button">{loading ? "Loading…" : "+ Add Product"}</Button></div>{error && <p className="mt-6 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{error}</p>}{feedback && <p className="mt-5 text-sm text-green-700">{feedback}</p>}<div className="mt-8 grid gap-4 lg:grid-cols-[minmax(0,1fr)_repeat(2,auto)]"><CustomerSearch onChange={setQuery} value={query} /><select aria-label="Filter by category" className={selectClass} onChange={(event) => { setCategoryFilter(event.target.value); setPage(1); }} value={categoryFilter}><option value="All">All Categories</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><select aria-label="Filter by availability" className={selectClass} onChange={(event) => { setAvailabilityFilter(event.target.value); setPage(1); }} value={availabilityFilter}><option>All</option><option>Available</option><option>Unavailable</option></select></div><div className="mt-4 text-sm text-brand-gray">{filtered.length} products</div><section className="mt-4 overflow-hidden bg-white shadow-sm" aria-label="Product list">{loading ? <div className="px-6 py-20 text-center text-sm text-brand-gray">Loading products…</div> : <><ProductTable onDelete={setDeleting} onEdit={(product) => { setEditing(product); setModalOpen(true); }} onToggleAvailability={toggle} products={visible} /><CustomerPagination currentPage={Math.min(page, totalPages)} onPageChange={setPage} totalPages={totalPages} /></>}</section>{modalOpen && <ProductFormModal categories={categories} isSubmitting={submitting} onClose={() => { setModalOpen(false); setEditing(undefined); }} onSubmit={save} product={editing} />}{deleting && <DeleteProductDialog onCancel={() => setDeleting(undefined)} onConfirm={remove} product={deleting} />}</Container>;
}
