"use client";
import { useEffect, useState } from "react";
import { CloseIcon } from "@/components/ui/icons";
import { ImageUploadField } from "@/components/admin/image-upload-field";
import type { AdminService, ServiceStatus } from "@/types/admin-service";
type FormService = AdminService & { imageFile?: File; removeImage?: boolean };
type Props = { service?: AdminService; isSubmitting?: boolean; onClose: () => void; onSubmit: (service: FormService) => void };
export function ServiceFormModal({ service, isSubmitting, onClose, onSubmit }: Props) {
  const [values, setValues] = useState({ name: service?.name ?? "", description: service?.description ?? "", price: service ? String(service.price) : "", sessions: service ? String(service.sessions) : "10", status: service?.status ?? "Active" as ServiceStatus }); const [imageFile, setImageFile] = useState<File>(); const [removeImage, setRemoveImage] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; document.addEventListener("keydown", close); document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", close); document.body.style.overflow = ""; }; }, [onClose]);
  function update(key: string, value: string) { setValues((current) => ({ ...current, [key]: value })); setError(""); }
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const name = values.name.trim(); const price = Number(values.price); const sessions = Number(values.sessions); if (!name) return setError("Service name is required."); if (!Number.isFinite(price) || price < 0) return setError("Price must be a valid non-negative number."); if (!Number.isInteger(sessions) || sessions < 1) return setError("Sessions must be a positive whole number."); onSubmit({ id: service?.id ?? "", name, description: values.description.trim(), price, sessions, image: service?.image ?? "", status: values.status, createdAt: service?.createdAt ?? "", updatedAt: service?.updatedAt ?? "", imageFile, removeImage: removeImage && !imageFile }); }
  const input = "mt-2 h-11 w-full rounded-md border border-black/10 bg-white px-4 text-sm outline-none focus:border-brand-purple";
  return <div aria-labelledby="service-form-title" aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-brand-dark/45 px-5 py-8" role="dialog"><div className="my-auto w-full max-w-2xl bg-white p-7 shadow-brand sm:p-10"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-brand-purple">Service management</p><h2 className="mt-2 text-3xl" id="service-form-title">{service ? "Edit Service" : "Add Service"}</h2></div><button aria-label="Close service form" className="h-9 w-9 text-brand-gray" onClick={onClose} type="button"><CloseIcon /></button></div><form className="mt-8 grid gap-5 sm:grid-cols-2" onSubmit={submit}><label className="text-sm font-semibold sm:col-span-2">Service Name<input className={input} onChange={(event) => update("name", event.target.value)} value={values.name} /></label><label className="text-sm font-semibold sm:col-span-2">Description<textarea className="mt-2 min-h-24 w-full resize-y rounded-md border border-black/10 p-4 text-sm outline-none focus:border-brand-purple" maxLength={500} onChange={(event) => update("description", event.target.value)} value={values.description} /></label><label className="text-sm font-semibold">Price<input className={input} min="0" step="0.01" type="number" onChange={(event) => update("price", event.target.value)} value={values.price} /></label><label className="text-sm font-semibold">Sessions<input className={input} min="1" step="1" type="number" onChange={(event) => update("sessions", event.target.value)} value={values.sessions} /></label><label className="text-sm font-semibold">Availability<select className={input} onChange={(event) => update("status", event.target.value)} value={values.status}><option>Active</option><option>Inactive</option></select></label><ImageUploadField disabled={isSubmitting} existingImage={service?.image} file={imageFile} label="Service image" onFileChange={(file) => { setImageFile(file); setRemoveImage(false); }} onRemove={() => setRemoveImage(true)} />{error && <p className="text-xs text-red-600 sm:col-span-2">{error}</p>}<div className="flex justify-end gap-3 sm:col-span-2"><button className="min-h-12 border border-brand-purple px-7 text-[11px] font-semibold uppercase text-brand-purple" onClick={onClose} type="button">Cancel</button><button className="min-h-12 bg-brand-purple px-7 text-[11px] font-semibold uppercase text-white disabled:opacity-60" disabled={isSubmitting} type="submit">{isSubmitting ? "Saving…" : service ? "Save Changes" : "Add Service"}</button></div></form></div></div>;
}
