"use client";
import { useEffect, useMemo, useState } from "react";
import { createService, deleteService, getServices, updateService, updateServiceAvailability } from "@/api/services.api";
import { CustomerPagination } from "@/components/admin/customers/customer-pagination";
import { CustomerSearch } from "@/components/admin/customers/customer-search";
import { Button } from "@/components/ui/button";
import { Container } from "@/components/ui/container";
import type { AdminService } from "@/types/admin-service";
import { DeleteServiceDialog } from "./delete-service-dialog";
import { ServiceFormModal } from "./service-form-modal";
import { ServiceTable } from "./service-table";
const PAGE_SIZE = 10;
export function ServicesPage() {
  const [services, setServices] = useState<AdminService[]>([]); const [query, setQuery] = useState(""); const [debouncedQuery, setDebouncedQuery] = useState(""); const [status, setStatus] = useState("All"); const [page, setPage] = useState(1); const [editing, setEditing] = useState<AdminService>(); const [deleting, setDeleting] = useState<AdminService>(); const [modalOpen, setModalOpen] = useState(false); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(""); const [feedback, setFeedback] = useState("");
  useEffect(() => { getServices(true).then(setServices).catch((e: unknown) => setError(e instanceof Error ? e.message : "Unable to load services.")).finally(() => setLoading(false)); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { setDebouncedQuery(query.trim().toLowerCase()); setPage(1); }, 400); return () => window.clearTimeout(timer); }, [query]);
  const filtered = useMemo(() => services.filter((service) => (!debouncedQuery || `${service.name} ${service.description} ${service.id}`.toLowerCase().includes(debouncedQuery)) && (status === "All" || service.status === status)), [services, debouncedQuery, status]); const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  async function save(service: AdminService & { imageFile?: File; removeImage?: boolean }) { try { setSubmitting(true); setError(""); const data = { name: service.name, description: service.description, price: service.price, sessions: service.sessions, imageFile: service.imageFile, removeImage: service.removeImage, status: service.status === "Active" }; const saved = editing ? await updateService(service.id, data) : await createService(data); setServices((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [saved, ...current]); setModalOpen(false); setEditing(undefined); setFeedback(editing ? "Service updated successfully." : "Service created successfully."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save service."); } finally { setSubmitting(false); } }
  async function remove() { if (!deleting) return; try { setSubmitting(true); await deleteService(deleting.id); setServices((current) => current.filter((item) => item.id !== deleting.id)); setDeleting(undefined); setFeedback("Service deleted successfully."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to delete service."); } finally { setSubmitting(false); } }
  async function toggle(service: AdminService) { try { setSubmitting(true); const saved = await updateServiceAvailability(service.id, service.status !== "Active"); setServices((current) => current.map((item) => item.id === saved.id ? saved : item)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update service availability."); } finally { setSubmitting(false); } }
  return <Container className="py-10 sm:py-12 lg:py-16"><div className="flex flex-col gap-7 border-b border-black/10 pb-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-brand-purple">Sattva administration</p><h1 className="mt-3 text-4xl sm:text-5xl">Services</h1><p className="mt-3 text-sm text-brand-gray">Manage guided yoga and meditation services.</p></div><Button disabled={submitting || loading} onClick={() => { setEditing(undefined); setModalOpen(true); }} type="button">{loading ? "Loading…" : "+ Add Service"}</Button></div>{error && <p className="mt-6 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{error}</p>}{feedback && <p className="mt-5 text-sm text-green-700">{feedback}</p>}<div className="mt-8 grid gap-4 lg:grid-cols-[minmax(0,1fr)_auto]"><CustomerSearch onChange={setQuery} value={query} /><select aria-label="Filter services by status" className="h-12 rounded-md border border-black/10 bg-white px-4 text-sm outline-none focus:border-brand-purple" onChange={(event) => { setStatus(event.target.value); setPage(1); }} value={status}><option>All</option><option>Active</option><option>Inactive</option></select></div><div className="mt-4 text-sm text-brand-gray">{filtered.length} services</div><section aria-label="Service list" className="mt-4 overflow-hidden bg-white shadow-sm">{loading ? <div className="px-6 py-20 text-center text-sm text-brand-gray">Loading services…</div> : <><ServiceTable onDelete={setDeleting} onEdit={(service) => { setEditing(service); setModalOpen(true); }} onToggleAvailability={toggle} services={visible} /><CustomerPagination currentPage={Math.min(page, totalPages)} onPageChange={setPage} totalPages={totalPages} /></>}</section>{modalOpen && <ServiceFormModal isSubmitting={submitting} onClose={() => { setModalOpen(false); setEditing(undefined); }} onSubmit={save} service={editing} />}{deleting && <DeleteServiceDialog onCancel={() => setDeleting(undefined)} onConfirm={remove} service={deleting} />}</Container>;
}
