import Image from "next/image";
import Link from "next/link";
import { EditIcon, TrashIcon } from "@/components/ui/icons";
import type { AdminService } from "@/types/admin-service";
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const date = (value: string) => new Intl.DateTimeFormat("en-US", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value));
export function ServiceTable({ services, onEdit, onDelete, onToggleAvailability }: { services: AdminService[]; onEdit: (service: AdminService) => void; onDelete: (service: AdminService) => void; onToggleAvailability: (service: AdminService) => void }) {
  if (!services.length) return <div className="px-6 py-20 text-center"><p className="font-serif text-2xl">No services found</p><p className="mt-2 text-sm text-brand-gray">Try adjusting your search.</p></div>;
  return <div className="overflow-x-auto"><table className="w-full min-w-[1120px] border-collapse text-left"><thead><tr className="border-b border-black/10 text-[10px] font-semibold uppercase tracking-[0.16em] text-brand-gray"><th className="px-6 py-4">Service</th><th className="px-6 py-4">Trainer</th><th className="px-6 py-4">Price / session</th><th className="px-6 py-4">Status</th><th className="px-6 py-4">Availability</th><th className="px-6 py-4">Created</th><th className="px-6 py-4 text-right">Actions</th></tr></thead><tbody>{services.map((service) => <tr className="border-b border-black/5 transition-colors last:border-0 hover:bg-brand-light-gray/70" key={service.id}><td className="px-6 py-4"><div className="flex items-center gap-3"><div className="relative h-12 w-12 shrink-0 overflow-hidden rounded-md bg-brand-light-gray"><Image alt={service.name} className="object-cover" fill sizes="48px" src={service.image} unoptimized /></div><div><Link className="max-w-[250px] truncate text-sm font-semibold hover:text-brand-purple" href={`/services/${service.id}`}>{service.name}</Link><p className="max-w-[280px] truncate text-xs text-brand-gray">{service.description}</p></div></div></td><td className="px-6 py-4 text-sm text-brand-gray">{service.trainer?.name ?? "Unassigned"}</td><td className="whitespace-nowrap px-6 py-4 text-sm font-semibold">{money.format(service.price)}</td><td className="px-6 py-4"><span className={`rounded-full px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.1em] ${service.status === "Active" ? "bg-green-50 text-green-700" : "bg-gray-100 text-gray-600"}`}>{service.status}</span></td><td className="px-6 py-4"><button aria-label={`${service.status === "Active" ? "Mark" : "Make"} ${service.name} ${service.status === "Active" ? "unavailable" : "available"}`} className={`relative h-6 w-11 rounded-full ${service.status === "Active" ? "bg-brand-purple" : "bg-brand-gray/50"}`} onClick={() => onToggleAvailability(service)} type="button"><span className={`absolute top-1 h-4 w-4 rounded-full bg-white ${service.status === "Active" ? "left-6" : "left-1"}`} /></button></td><td className="whitespace-nowrap px-6 py-4 text-sm text-brand-gray">{date(service.createdAt)}</td><td className="px-6 py-4"><div className="flex justify-end gap-2"><button aria-label={`Edit ${service.name}`} className="inline-flex h-9 w-9 items-center justify-center rounded-md text-brand-gray hover:bg-brand-purple/10 hover:text-brand-purple" onClick={() => onEdit(service)} type="button"><EditIcon /></button><button aria-label={`Delete ${service.name}`} className="inline-flex h-9 w-9 items-center justify-center rounded-md text-brand-gray hover:bg-red-50 hover:text-red-600" onClick={() => onDelete(service)} type="button"><TrashIcon /></button></div></td></tr>)}</tbody></table></div>;
}
