import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PrismaService } from '../../database/prisma.service.js';
import { MailService } from '../../mail/mail.service.js';
import { bookingConfirmationCustomer, bookingNewAdmin, sessionConfirmedAdmin, sessionConfirmedCustomer, sessionReviewedCustomer } from '../../templates/service-booking-email.templates.js';

@Injectable()
export class BookingEmailService {
  private readonly logger = new Logger(BookingEmailService.name);
  constructor(private readonly prisma: PrismaService, private readonly mail: MailService, private readonly config: ConfigService) {}
  private url(base: string | undefined, path: string) { return `${(base ?? '').replace(/\/$/, '')}${path}`; }
  private async booking(id: string) { return this.prisma.serviceBooking.findUnique({ where: { id }, include: { service: { select: { name: true } }, trainer: { select: { id: true, name: true, email: true, phone: true } }, sessions: { orderBy: { scheduledAt: 'asc' } }, order: { include: { payment: true } } } }); }
  private async send(kind: string, bookingId: string, recipient: string, message: { subject: string; html: string; text: string }) { try { await this.mail.sendMail({ to: recipient, ...message }); this.logger.log(`Sent ${kind} bookingId=${bookingId} recipient=${recipient}`); } catch (error) { this.logger.error(`Failed to send ${kind} bookingId=${bookingId} recipient=${recipient}`, error instanceof Error ? error.stack : String(error)); } }
  private async safe(kind: string, bookingId: string, task: () => Promise<void>) { try { await task(); } catch (error) { this.logger.error(`Failed to prepare ${kind} bookingId=${bookingId}`, error instanceof Error ? error.stack : String(error)); } }
  async sendBookingConfirmationToCustomer(bookingId: string, otp: string) { await this.safe('booking confirmation customer email', bookingId, async () => { const booking = await this.booking(bookingId); if (!booking?.order?.email) return; const message = bookingConfirmationCustomer(booking, otp, this.url(this.config.get<string>('mail.frontendUrl'), '/profile/services')); await this.send('booking confirmation customer email', bookingId, booking.order.email, message); }); }
  async sendNewBookingToAdmin(bookingId: string) { await this.safe('new booking admin email', bookingId, async () => { const booking = await this.booking(bookingId); const admin = this.config.get<string>('mail.adminEmail'); if (!booking || !admin) return; const message = bookingNewAdmin(booking, this.url(this.config.get<string>('mail.adminUrl'), `/service-bookings/${encodeURIComponent(bookingId)}`)); await this.send('new booking admin email', bookingId, admin, message); }); }
  async sendSessionConfirmed(bookingId: string, confirmedAt: Date) { await this.safe('session confirmation emails', bookingId, async () => { const booking = await this.booking(bookingId); const admin = this.config.get<string>('mail.adminEmail'); if (!booking?.order?.email) return; const customerMessage = sessionConfirmedCustomer(booking, confirmedAt, this.url(this.config.get<string>('mail.frontendUrl'), '/profile/services')); await this.send('session confirmation customer email', bookingId, booking.order.email, customerMessage); if (admin) await this.send('session confirmation admin email', bookingId, admin, sessionConfirmedAdmin(booking, confirmedAt, this.url(this.config.get<string>('mail.adminUrl'), `/service-bookings/${encodeURIComponent(bookingId)}`))); }); }
  async sendSessionReviewed(bookingId: string, decision: string, reviewedAt: Date, reason?: string) { await this.safe('session review customer email', bookingId, async () => { const booking = await this.booking(bookingId); if (!booking?.order?.email) return; const message = sessionReviewedCustomer(booking, decision, reviewedAt, reason, this.url(this.config.get<string>('mail.frontendUrl'), '/profile/services')); await this.send('session review customer email', bookingId, booking.order.email, message); }); }
}
