"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { getAdminServiceBookingHistoryList } from "@/api/service-bookings.api";
import { CustomerPagination } from "@/components/admin/customers/customer-pagination";
import { Container } from "@/components/ui/container";

const date = (value: string) => new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }).format(new Date(value));

export function ServiceBookingHistoryPage() { const [result, setResult] = useState<Awaited<ReturnType<typeof getAdminServiceBookingHistoryList>>>(); const [page, setPage] = useState(1); const [error, setError] = useState(""); useEffect(() => { getAdminServiceBookingHistoryList(page).then(setResult).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load action history.")); }, [page]); return <Container className="py-10 sm:py-12 lg:py-16"><Link className="text-[10px] font-semibold uppercase tracking-[0.14em] text-brand-purple" href="/admin/service-bookings">← Booked services dashboard</Link><header className="mt-5 border-b border-black/10 pb-8"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-brand-purple">Service operations</p><h1 className="mt-3 text-4xl sm:text-5xl">Action History</h1><p className="mt-3 text-sm text-brand-gray">Immutable operational events for service bookings.</p></header>{error && <p className="mt-6 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<section className="mt-8 overflow-hidden bg-white shadow-sm">{!result ? <div className="px-6 py-20 text-center text-sm text-brand-gray">Loading action history…</div> : !result.items.length ? <div className="px-6 py-20 text-center font-serif text-2xl">No service-booking actions found.</div> : <><div className="divide-y divide-black/10">{result.items.map((event) => <div className="flex flex-col justify-between gap-3 px-6 py-5 sm:flex-row" key={event.id}><div><div className="flex flex-wrap items-center gap-3"><p className="font-semibold">{event.action.replaceAll("_", " ")}</p><span className="rounded-full bg-brand-purple/10 px-2.5 py-1 text-[10px] font-semibold uppercase text-brand-purple">{event.actorType}</span></div><p className="mt-2 text-sm text-brand-gray">{event.description}</p><Link className="mt-2 inline-block text-xs font-semibold text-brand-purple" href={`/admin/service-bookings/${event.booking.id}`}>Booking {event.booking.id.slice(0, 8)} · {event.booking.service.name}</Link></div><time className="whitespace-nowrap text-xs text-brand-gray">{date(event.performedAt)}</time></div>)}</div><CustomerPagination currentPage={result.pagination.page} onPageChange={setPage} totalPages={result.pagination.totalPages} /></>}</section></Container>; }
