"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { getAdminServiceBookingStats, getAdminServiceBookings, type AdminServiceBooking, type ServiceBookingStats } from "@/api/service-bookings.api";
import { getServices } from "@/api/services.api";
import { getTrainers } from "@/api/trainers.api";
import { CustomerPagination } from "@/components/admin/customers/customer-pagination";
import { CustomerSearch } from "@/components/admin/customers/customer-search";
import { Container } from "@/components/ui/container";

const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);
const date = (value: string) => new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }).format(new Date(value));
const labels = [["Total Bookings", "total"], ["Pending", "pending"], ["Confirmed", "scheduled"], ["Upcoming Sessions", "upcoming"], ["Completed", "completed"], ["Cancelled", "cancelled"]] as const;
const statusLabels: Record<string, string> = { PENDING_PAYMENT: "Pending", SCHEDULED: "Confirmed", COMPLETED: "Completed", CANCELLED: "Cancelled" };

function Stats({ stats }: { stats: ServiceBookingStats }) { return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{labels.map(([label, key]) => <div className="bg-white p-5 shadow-sm" key={label}><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-brand-gray">{label}</p><p className="mt-3 font-serif text-3xl text-brand-dark">{stats[key]}</p></div>)}<div className="bg-brand-purple p-5 text-white shadow-sm"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-white/70">Revenue</p><p className="mt-3 font-serif text-3xl">{money(stats.revenue)}</p></div></div>; }

function BookingTable({ bookings }: { bookings: AdminServiceBooking[] }) { if (!bookings.length) return <div className="px-6 py-20 text-center"><p className="font-serif text-2xl">No service bookings found.</p><p className="mt-2 text-sm text-brand-gray">Try adjusting your search or filters.</p></div>; return <div className="overflow-x-auto"><table className="w-full min-w-[1250px] border-collapse text-left"><thead><tr className="border-b border-black/10 text-[10px] font-semibold uppercase tracking-[0.16em] text-brand-gray"><th className="px-6 py-4">Booking</th><th className="px-6 py-4">Customer</th><th className="px-6 py-4">Service</th><th className="px-6 py-4">Trainer</th><th className="px-6 py-4">Sessions</th><th className="px-6 py-4">Schedule</th><th className="px-6 py-4">Amount</th><th className="px-6 py-4">Payment</th><th className="px-6 py-4">Status</th><th className="px-6 py-4">Created</th><th className="px-6 py-4">Action</th></tr></thead><tbody>{bookings.map((booking) => <tr className="border-b border-black/5 last:border-0" key={booking.id}><td className="px-6 py-5 text-sm font-semibold">{booking.id.slice(0, 8)}</td><td className="px-6 py-5"><p className="text-sm font-semibold">{booking.customer.name}</p><p className="text-xs text-brand-gray">{booking.customer.email}</p></td><td className="px-6 py-5 text-sm">{booking.service?.name ?? "—"}</td><td className="px-6 py-5 text-sm">{booking.trainer.name}</td><td className="px-6 py-5 text-sm">{booking.quantity}</td><td className="whitespace-nowrap px-6 py-5 text-xs text-brand-gray">{booking.sessions[0] ? date(booking.sessions[0].scheduledAt) : "—"}{booking.sessions.length > 1 && ` +${booking.sessions.length - 1}`}</td><td className="whitespace-nowrap px-6 py-5 text-sm font-semibold">{money(booking.totalAmount)}</td><td className="px-6 py-5 text-xs">{booking.payment?.status ?? "Pending"}</td><td className="px-6 py-5 text-xs font-semibold">{statusLabels[booking.status] ?? booking.status}</td><td className="whitespace-nowrap px-6 py-5 text-xs text-brand-gray">{date(booking.createdAt)}</td><td className="px-6 py-5"><Link className="text-[10px] font-semibold uppercase tracking-[0.12em] text-brand-purple" href={`/admin/service-bookings/${booking.id}`}>View</Link></td></tr>)}</tbody></table></div>; }

export function ServiceBookingsPage() {
  const [bookings, setBookings] = useState<AdminServiceBooking[]>([]); const [stats, setStats] = useState<ServiceBookingStats>(); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [paymentStatus, setPaymentStatus] = useState(""); const [serviceId, setServiceId] = useState(""); const [trainerId, setTrainerId] = useState(""); const [services, setServices] = useState<Array<{ id: string; name: string }>>([]); const [trainers, setTrainers] = useState<Array<{ id: string; name: string }>>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(() => { setLoading(true); setError(""); Promise.all([getAdminServiceBookings({ page, limit: 10, search: query, status, paymentStatus, serviceId, trainerId }), getAdminServiceBookingStats()]).then(([result, nextStats]) => { setBookings(result.items); setTotalPages(result.pagination.totalPages); setStats(nextStats); }).catch((e: unknown) => setError(e instanceof Error ? e.message : "Unable to load service bookings.")).finally(() => setLoading(false)); }, [page, paymentStatus, query, serviceId, status, trainerId]);
  useEffect(() => { load(); }, [load]); useEffect(() => { Promise.all([getServices(true), getTrainers()]).then(([serviceRows, trainerRows]) => { setServices(serviceRows.map((item) => ({ id: item.id, name: item.name }))); setTrainers(trainerRows.map((item) => ({ id: item.id, name: item.name }))); }).catch(() => undefined); }, []);
  return <Container className="py-10 sm:py-12 lg:py-16"><header className="border-b border-black/10 pb-8"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-brand-purple">Sattva administration</p><h1 className="mt-3 text-4xl sm:text-5xl">Service Bookings</h1><p className="mt-3 text-sm text-brand-gray">Manage customer service bookings, trainers, sessions, schedules and booking status.</p></header>{error && <div className="mt-6 flex justify-between border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><span>{error}</span><button className="font-semibold underline" onClick={load} type="button">Retry</button></div>}{stats && <section className="mt-8"><Stats stats={stats} /></section>}<section className="mt-8 flex flex-col gap-4 lg:flex-row lg:items-center"><CustomerSearch onChange={(value) => { setPage(1); setQuery(value); }} value={query} /><select aria-label="Filter booking status" className="h-12 rounded-md border border-black/10 bg-white px-4 text-sm" onChange={(event) => { setPage(1); setStatus(event.target.value); }} value={status}><option value="">All statuses</option><option value="PENDING_PAYMENT">Pending</option><option value="SCHEDULED">Confirmed / Upcoming</option><option value="COMPLETED">Completed</option><option value="CANCELLED">Cancelled</option></select><select aria-label="Filter payment status" className="h-12 rounded-md border border-black/10 bg-white px-4 text-sm" onChange={(event) => { setPage(1); setPaymentStatus(event.target.value); }} value={paymentStatus}><option value="">All payments</option><option value="PENDING">Pending</option><option value="PAID">Paid</option><option value="FAILED">Failed</option><option value="REFUNDED">Refunded</option></select><select aria-label="Filter service" className="h-12 rounded-md border border-black/10 bg-white px-4 text-sm" onChange={(event) => { setPage(1); setServiceId(event.target.value); }} value={serviceId}><option value="">All services</option>{services.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Filter trainer" className="h-12 rounded-md border border-black/10 bg-white px-4 text-sm" onChange={(event) => { setPage(1); setTrainerId(event.target.value); }} value={trainerId}><option value="">All trainers</option>{trainers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></section><section aria-label="Service bookings list" className="mt-6 overflow-hidden bg-white shadow-sm">{loading ? <div className="px-6 py-20 text-center text-sm text-brand-gray">Loading service bookings…</div> : <><BookingTable bookings={bookings} /><CustomerPagination currentPage={Math.min(page, totalPages)} onPageChange={setPage} totalPages={totalPages} /></>}</section></Container>;
}
