"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { getAdminServiceBookings, type AdminServiceBooking } from "@/api/service-bookings.api";
import { CustomerPagination } from "@/components/admin/customers/customer-pagination";
import { Container } from "@/components/ui/container";

const date = (value: string) => new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }).format(new Date(value));
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);

type Queue = "pending" | "confirmed" | "images" | "review" | "completed" | "history";
const config: Record<Queue, { title: string; description: string; query: Record<string, string>; empty: string }> = {
  pending: { title: "Pending Trainer Confirmation", description: "Bookings that still need OTP confirmation from the assigned trainer.", query: { trainerConfirmation: "pending" }, empty: "All current service bookings have been confirmed by their trainers." },
  confirmed: { title: "Trainer Confirmed", description: "Bookings confirmed by trainers and ready for operational follow-up.", query: { trainerConfirmation: "confirmed" }, empty: "No trainer-confirmed bookings yet." },
  images: { title: "Image Review", description: "Review scene photos uploaded during trainer confirmation.", query: { imageReviewStatus: "PENDING" }, empty: "No trainer-uploaded session photos are currently waiting for review." },
  review: { title: "Admin Review", description: "Trainer-confirmed bookings awaiting an administrative decision.", query: { adminReviewStatus: "PENDING", trainerConfirmation: "confirmed" }, empty: "Nothing to review. There are no trainer-confirmed bookings waiting for admin review." },
  completed: { title: "Completed Services", description: "Bookings approved by an administrator.", query: { adminReviewStatus: "APPROVED" }, empty: "No approved service bookings yet." },
  history: { title: "Action History", description: "Open a booking to inspect its immutable operational history.", query: {}, empty: "No service-booking actions found." },
};

function Badge({ children, tone = "gray" }: { children: string; tone?: "gray" | "green" | "amber" | "red" | "purple" }) { const tones = { gray: "bg-black/5 text-brand-gray", green: "bg-green-100 text-green-800", amber: "bg-amber-100 text-amber-800", red: "bg-red-100 text-red-800", purple: "bg-brand-purple/10 text-brand-purple" }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.08em] ${tones[tone]}`}>{children}</span>; }

function Row({ booking }: { booking: AdminServiceBooking }) {
  const session = booking.sessions[0];
  return <tr className="border-b border-black/5 last:border-0"><td className="px-5 py-4 text-sm font-semibold">{booking.id.slice(0, 8)}</td><td className="px-5 py-4"><p className="text-sm font-semibold">{booking.service?.name ?? "—"}</p><p className="text-xs text-brand-gray">{booking.customer.name}</p></td><td className="px-5 py-4 text-sm">{booking.trainer.name}</td><td className="whitespace-nowrap px-5 py-4 text-xs text-brand-gray">{session ? date(session.scheduledAt) : "—"}</td><td className="px-5 py-4"><Badge tone={booking.trainerConfirmationStatus === "CONFIRMED" ? "green" : "amber"}>{booking.trainerConfirmationStatus}</Badge></td><td className="px-5 py-4"><Badge tone={booking.sceneImages.length ? "purple" : "gray"}>{booking.sceneImages.length ? `${booking.sceneImages.length} images` : "No images"}</Badge></td><td className="px-5 py-4"><Badge tone={booking.adminReviewStatus === "APPROVED" ? "green" : booking.adminReviewStatus === "REJECTED" ? "red" : "amber"}>{booking.adminReviewStatus.replace("_", " ")}</Badge></td><td className="whitespace-nowrap px-5 py-4 text-sm font-semibold">{money(booking.totalAmount)}</td><td className="px-5 py-4"><Link className="text-[10px] font-semibold uppercase tracking-[0.12em] text-brand-purple" href={`/admin/service-bookings/${booking.id}`}>View details</Link></td></tr>;
}

export function ServiceBookingQueuePage({ queue }: { queue: Queue }) {
  const current = config[queue]; const [bookings, setBookings] = useState<AdminServiceBooking[]>([]); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(() => { setLoading(true); getAdminServiceBookings({ page, limit: 20, search, ...current.query }).then((result) => { setBookings(result.items); setTotalPages(result.pagination.totalPages); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load service bookings.")).finally(() => setLoading(false)); }, [current.query, page, search]);
  useEffect(() => { load(); }, [load]);
  return <Container className="py-10 sm:py-12 lg:py-16"><Link className="text-[10px] font-semibold uppercase tracking-[0.14em] text-brand-purple" href="/admin/service-bookings">← Booked services dashboard</Link><header className="mt-5 flex flex-col justify-between gap-5 border-b border-black/10 pb-8 sm:flex-row sm:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-brand-purple">Service operations</p><h1 className="mt-3 text-4xl sm:text-5xl">{current.title}</h1><p className="mt-3 text-sm text-brand-gray">{current.description}</p></div><Link className="inline-flex min-h-11 items-center justify-center bg-brand-purple px-5 text-[10px] font-semibold uppercase tracking-[0.14em] text-white" href="/admin/service-bookings">All bookings</Link></header><div className="mt-8 flex flex-col gap-3 sm:flex-row"><input aria-label="Search service bookings" className="h-12 flex-1 border border-black/10 bg-white px-4 text-sm" onChange={(event) => { setPage(1); setSearch(event.target.value); }} placeholder="Search booking ID, customer, or trainer" value={search} /><button className="h-12 border border-brand-purple px-5 text-[10px] font-semibold uppercase tracking-[0.14em] text-brand-purple" onClick={load} type="button">Refresh</button></div>{error && <p className="mt-5 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<section className="mt-6 overflow-hidden bg-white shadow-sm">{loading ? <div className="px-6 py-20 text-center text-sm text-brand-gray">Loading bookings…</div> : !bookings.length ? <div className="px-6 py-20 text-center"><p className="font-serif text-2xl">{current.empty}</p><p className="mt-2 text-sm text-brand-gray">New operational items will appear here automatically.</p></div> : <><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left"><thead><tr className="border-b border-black/10 text-[10px] font-semibold uppercase tracking-[0.14em] text-brand-gray"><th className="px-5 py-4">Booking</th><th className="px-5 py-4">Service / customer</th><th className="px-5 py-4">Trainer</th><th className="px-5 py-4">Session</th><th className="px-5 py-4">Trainer confirmation</th><th className="px-5 py-4">Images</th><th className="px-5 py-4">Admin review</th><th className="px-5 py-4">Amount</th><th className="px-5 py-4">Actions</th></tr></thead><tbody>{bookings.map((booking) => <Row booking={booking} key={booking.id} />)}</tbody></table></div><CustomerPagination currentPage={page} onPageChange={setPage} totalPages={totalPages} /></>}</section></Container>;
}
