import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service.js';
import type { CreateOrderDto, CreateOrderItemDto } from './dto/create-order.dto.js';
import type { UpdateOrderStatusDto } from './dto/update-order-status.dto.js';
const orderSelect = { id: true, userId: true, status: true, subtotal: true, discount: true, total: true, name: true, email: true, phone: true, address: true, city: true, state: true, country: true, postalCode: true, createdAt: true, updatedAt: true, items: { orderBy: { createdAt: 'asc' as const }, select: { id: true, productId: true, serviceId: true, type: true, name: true, price: true, quantity: true, discount: true, total: true, product: { select: { imageUrl: true } }, service: { select: { imageUrl: true, sessions: true } } } }, payment: { select: { id: true, status: true, amount: true, currency: true, transactionId: true, paymentMethod: true, paidAt: true } } } as const;
function code(error: unknown) { return error && typeof error === 'object' && 'code' in error ? error.code : undefined; }
@Injectable()
export class OrdersService {
  constructor(private readonly prisma: PrismaService) {}
  async findAll(query: { status?: string; search?: string }) { const search = query.search?.trim(); const orders = await this.prisma.order.findMany({ where: { items: { some: { type: 'PRODUCT' }, none: { type: 'SERVICE' } }, ...(query.status ? { status: query.status as never } : {}), ...(search ? { OR: [{ id: { contains: search, mode: 'insensitive' } }, { name: { contains: search, mode: 'insensitive' } }, { email: { contains: search, mode: 'insensitive' } }] } : {}) }, orderBy: { createdAt: 'desc' }, select: orderSelect }); return orders.map((order) => this.present(order)); }
  async findForUser(userId: string) { const orders = await this.prisma.order.findMany({ where: { userId }, orderBy: { createdAt: 'desc' }, select: orderSelect }); return orders.map((order) => this.present(order)); }
  async findOne(id: string, userId?: string, isAdmin = false, productOnly = false) { const order = await this.prisma.order.findUnique({ where: { id }, select: orderSelect }); if (!order) throw new NotFoundException('Order not found'); if (productOnly && !order.items.some((item) => item.type === 'PRODUCT')) throw new NotFoundException('Product order not found'); if (!isAdmin && userId && order.userId !== userId) throw new ForbiddenException('You do not have access to this order'); return this.present(order); }
  async findOneForUser(id: string, userId: string) { const order = await this.prisma.order.findFirst({ where: { id, userId }, select: orderSelect }); if (!order) throw new NotFoundException('Order not found'); return this.present(order); }
  async create(userId: string | undefined, dto: CreateOrderDto) {
    if (!dto.items.length) throw new ConflictException('An order must contain at least one item');
    const itemData: Array<{ productId?: string; serviceId?: string; type: 'PRODUCT' | 'SERVICE'; name: string; price: number; quantity: number; discount: number; total: number }> = [];
    for (const item of dto.items) itemData.push(await this.resolveItem(item));
    const subtotal = itemData.reduce((sum, item) => sum + item.total, 0);
    const order = await this.prisma.$transaction(async (transaction) => { let resolvedUserId = userId; if (!resolvedUserId) { const normalizedEmail = dto.email.trim().toLowerCase(); const existing = await transaction.user.findUnique({ where: { email: normalizedEmail }, select: { id: true } }); resolvedUserId = existing?.id ?? (await transaction.user.create({ data: { name: dto.name.trim(), email: normalizedEmail, phone: dto.phone?.trim(), address1: dto.address.trim(), city: dto.city.trim(), state: dto.state.trim(), country: dto.country.trim(), postalCode: dto.postalCode.trim(), role: 'USER' }, select: { id: true } })).id; } const created = await transaction.order.create({ data: { userId: resolvedUserId, name: dto.name.trim(), email: dto.email.trim().toLowerCase(), phone: dto.phone?.trim(), address: dto.address.trim(), city: dto.city.trim(), state: dto.state.trim(), country: dto.country.trim(), postalCode: dto.postalCode.trim(), subtotal, discount: 0, total: subtotal, items: { create: itemData } }, select: { id: true } }); await transaction.payment.create({ data: { orderId: created.id, amount: subtotal, currency: 'USD' } }); return created; });
    return this.findOne(order.id, userId, Boolean(userId));
  }
  async updateStatus(id: string, dto: UpdateOrderStatusDto) { await this.findOne(id, undefined, true, true); try { return this.present(await this.prisma.order.update({ where: { id }, data: { status: dto.status }, select: orderSelect })); } catch (error: unknown) { if (code(error) === 'P2025') throw new NotFoundException('Order not found'); throw error; } }
  private async resolveItem(item: CreateOrderItemDto) { if (item.type === 'PRODUCT') { if (!item.productId || item.serviceId) throw new ConflictException('A product order item must reference one product'); const product = await this.prisma.product.findUnique({ where: { id: item.productId } }); if (!product) throw new NotFoundException('Product not found'); if (!product.isActive) throw new ConflictException(`${product.name} is unavailable`); const price = Number(product.price); return { productId: product.id, type: 'PRODUCT' as const, name: product.name, price, quantity: item.quantity, discount: 0, total: price * item.quantity }; } if (!item.serviceId || item.productId) throw new ConflictException('A service order item must reference one service'); const service = await this.prisma.service.findUnique({ where: { id: item.serviceId } }); if (!service) throw new NotFoundException('Service not found'); if (service.status !== 'ACTIVE') throw new ConflictException(`${service.name} is unavailable`); const price = Number(service.price); return { serviceId: service.id, type: 'SERVICE' as const, name: service.name, price, quantity: item.quantity, discount: 0, total: price * item.quantity }; }
  private present(order: any) { return { ...order, subtotal: Number(order.subtotal), discount: Number(order.discount), total: Number(order.total), items: order.items.map((item: any) => ({ id: item.id, productId: item.productId, serviceId: item.serviceId, type: item.type, name: item.name, price: Number(item.price), quantity: item.quantity, discount: Number(item.discount), total: Number(item.total), image: item.product?.imageUrl ?? item.service?.imageUrl ?? null, sessions: item.service?.sessions ?? null })), payment: order.payment ? { ...order.payment, amount: Number(order.payment.amount) } : null }; }
}
