import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PrismaService } from '../../database/prisma.service.js';
import type { CreateOrderDto, CreateOrderItemDto } from './dto/create-order.dto.js';
import type { UpdateOrderStatusDto } from './dto/update-order-status.dto.js';
const orderSelect = { id: true, userId: true, status: true, subtotal: true, discount: true, shippingCharge: true, total: true, name: true, email: true, phone: true, address: true, city: true, state: true, country: true, postalCode: true, createdAt: true, updatedAt: true, items: { orderBy: { createdAt: 'asc' as const }, select: { id: true, productId: true, serviceId: true, type: true, name: true, price: true, quantity: true, discount: true, total: true, product: { select: { imageUrl: true } }, service: { select: { imageUrl: true, sessions: true } } } }, payment: { select: { id: true, status: true, amount: true, currency: true, transactionId: true, paymentMethod: true, paidAt: true } } } as const;
const productOnly = { items: { some: { type: 'PRODUCT' as const }, none: { type: 'SERVICE' as const } } };
const transitions: Record<string, string[]> = { NEW: ['CONFIRMED', 'CANCELLED'], CONFIRMED: ['PROCESSING', 'CANCELLED'], PROCESSING: ['SHIPPED', 'CANCELLED'], SHIPPED: ['OUT_FOR_DELIVERY', 'CANCELLED', 'REFUNDED'], OUT_FOR_DELIVERY: ['DELIVERED', 'CANCELLED'], DELIVERED: ['REFUNDED'], CANCELLED: ['REFUNDED'], REFUNDED: [] };
function code(error: unknown) { return error && typeof error === 'object' && 'code' in error ? error.code : undefined; }
@Injectable()
export class OrdersService {
  constructor(private readonly prisma: PrismaService, private readonly config: ConfigService) {}
  async findAll(query: { status?: string; search?: string }) { const search = query.search?.trim(); const orders = await this.prisma.order.findMany({ where: { ...productOnly, ...(query.status ? { status: query.status as never } : {}), ...(search ? { OR: [{ id: { contains: search, mode: 'insensitive' } }, { name: { contains: search, mode: 'insensitive' } }, { email: { contains: search, mode: 'insensitive' } }] } : {}) }, orderBy: { createdAt: 'desc' }, select: orderSelect }); return orders.map((order) => this.present(order)); }
  async adminList(query: { page?: string; limit?: string; status?: string; search?: string; sort?: string }) { const page = Math.max(1, Number(query.page) || 1); const limit = Math.min(50, Math.max(1, Number(query.limit) || 20)); const search = query.search?.trim(); const where: any = { ...productOnly, ...(query.status ? { status: query.status as never } : {}), ...(search ? { OR: [{ id: { contains: search, mode: 'insensitive' } }, { name: { contains: search, mode: 'insensitive' } }, { email: { contains: search, mode: 'insensitive' } }, { phone: { contains: search, mode: 'insensitive' } }] } : {}) }; const orderBy = query.sort === 'oldest' ? { createdAt: 'asc' as const } : query.sort === 'highest' ? { total: 'desc' as const } : query.sort === 'lowest' ? { total: 'asc' as const } : query.sort === 'updated' ? { updatedAt: 'desc' as const } : { createdAt: 'desc' as const }; const [orders, total] = await Promise.all([this.prisma.order.findMany({ where, skip: (page - 1) * limit, take: limit, orderBy, select: orderSelect }), this.prisma.order.count({ where })]); return { items: orders.map((order) => this.present(order)), pagination: { page, limit, total, totalPages: Math.max(1, Math.ceil(total / limit)) } }; }
  async findForUser(userId: string) { const orders = await this.prisma.order.findMany({ where: { userId }, orderBy: { createdAt: 'desc' }, select: orderSelect }); return orders.map((order) => this.present(order)); }
  async findOne(id: string, userId?: string, isAdmin = false, productOnly = false) { const order = await this.prisma.order.findUnique({ where: { id }, select: orderSelect }); if (!order) throw new NotFoundException('Order not found'); if (productOnly && (!order.items.some((item) => item.type === 'PRODUCT') || order.items.some((item) => item.type === 'SERVICE'))) throw new NotFoundException('Product order not found'); if (!isAdmin && userId && order.userId !== userId) throw new ForbiddenException('You do not have access to this order'); return this.present(order); }
  async findOneForUser(id: string, userId: string) { const order = await this.prisma.order.findFirst({ where: { id, userId }, select: orderSelect }); if (!order) throw new NotFoundException('Order not found'); return this.present(order); }
  async create(userId: string | undefined, dto: CreateOrderDto) {
    if (!dto.items.length) throw new ConflictException('An order must contain at least one item');
    const itemData: Array<{ productId?: string; serviceId?: string; type: 'PRODUCT' | 'SERVICE'; name: string; price: number; quantity: number; discount: number; total: number }> = [];
    for (const item of dto.items) itemData.push(await this.resolveItem(item));
    const subtotal = itemData.reduce((sum, item) => sum + item.total, 0);
    const shippingCharge = Math.max(0, Number(this.config.get<number>('orders.shippingCharge') ?? 0));
    const total = subtotal + shippingCharge;
    const order = await this.prisma.$transaction(async (transaction) => { let resolvedUserId = userId; if (!resolvedUserId) { const normalizedEmail = dto.email.trim().toLowerCase(); const existing = await transaction.user.findUnique({ where: { email: normalizedEmail }, select: { id: true } }); resolvedUserId = existing?.id ?? (await transaction.user.create({ data: { name: dto.name.trim(), email: normalizedEmail, phone: dto.phone?.trim(), address1: dto.address.trim(), city: dto.city.trim(), state: dto.state.trim(), country: dto.country.trim(), postalCode: dto.postalCode.trim(), role: 'USER' }, select: { id: true } })).id; } const created = await transaction.order.create({ data: { userId: resolvedUserId, status: 'NEW', name: dto.name.trim(), email: dto.email.trim().toLowerCase(), phone: dto.phone?.trim(), address: dto.address.trim(), city: dto.city.trim(), state: dto.state.trim(), country: dto.country.trim(), postalCode: dto.postalCode.trim(), subtotal, discount: 0, shippingCharge, total, items: { create: itemData } }, select: { id: true } }); await transaction.payment.create({ data: { orderId: created.id, amount: total, currency: 'USD' } }); await transaction.orderStatusHistory.create({ data: { orderId: created.id, newStatus: 'NEW', actorType: userId ? 'CUSTOMER' : 'SYSTEM', changedBy: userId, reason: 'Order created.' } }); return created; });
    return this.findOne(order.id, userId, Boolean(userId));
  }
  async updateStatus(id: string, dto: UpdateOrderStatusDto, adminId: string) { const current = await this.prisma.order.findFirst({ where: { id, ...productOnly }, select: { status: true, payment: { select: { status: true } } } }); if (!current) throw new NotFoundException('Product order not found'); if (!(transitions[current.status] ?? []).includes(dto.status)) throw new ConflictException(`Cannot change order from ${current.status} to ${dto.status}`); if (dto.status === 'CANCELLED' && !dto.reason?.trim()) throw new BadRequestException('A cancellation reason is required'); if (dto.status === 'REFUNDED' && current.payment?.status !== 'REFUNDED') throw new ConflictException('Refund must be completed through the payment system before the order is marked refunded'); const updated = await this.prisma.$transaction(async (tx) => { const saved = await tx.order.update({ where: { id }, data: { status: dto.status }, select: orderSelect }); await tx.orderStatusHistory.create({ data: { orderId: id, previousStatus: current.status, newStatus: dto.status, changedBy: adminId, actorType: 'ADMIN', reason: dto.reason?.trim() } }); return saved; }); return this.present(updated); }
  async history(id: string) { const order = await this.prisma.order.findFirst({ where: { id, ...productOnly }, select: { id: true } }); if (!order) throw new NotFoundException('Product order not found'); return this.prisma.orderStatusHistory.findMany({ where: { orderId: id }, orderBy: { changedAt: 'asc' } }); }
  async adminStats() { const rows = await this.prisma.order.groupBy({ by: ['status'], where: productOnly, _count: { _all: true }, _sum: { total: true, shippingCharge: true } }); const counts = Object.fromEntries(rows.map((row) => [row.status, row._count._all])); const totals = rows.reduce((result, row) => ({ total: result.total + Number(row._sum.total ?? 0), shipping: result.shipping + Number(row._sum.shippingCharge ?? 0) }), { total: 0, shipping: 0 }); return { counts, totalValue: totals.total, totalShipping: totals.shipping, totalOrders: rows.reduce((sum, row) => sum + row._count._all, 0) }; }
  private async resolveItem(item: CreateOrderItemDto) { if (item.type === 'PRODUCT') { if (!item.productId || item.serviceId) throw new ConflictException('A product order item must reference one product'); const product = await this.prisma.product.findUnique({ where: { id: item.productId } }); if (!product) throw new NotFoundException('Product not found'); if (!product.isActive) throw new ConflictException(`${product.name} is unavailable`); const price = Number(product.price); return { productId: product.id, type: 'PRODUCT' as const, name: product.name, price, quantity: item.quantity, discount: 0, total: price * item.quantity }; } if (!item.serviceId || item.productId) throw new ConflictException('A service order item must reference one service'); const service = await this.prisma.service.findUnique({ where: { id: item.serviceId } }); if (!service) throw new NotFoundException('Service not found'); if (service.status !== 'ACTIVE') throw new ConflictException(`${service.name} is unavailable`); const price = Number(service.price); return { serviceId: service.id, type: 'SERVICE' as const, name: service.name, price, quantity: item.quantity, discount: 0, total: price * item.quantity }; }
  private present(order: any) { return { ...order, subtotal: Number(order.subtotal), discount: Number(order.discount), shippingCharge: Number(order.shippingCharge ?? 0), total: Number(order.total), items: order.items.map((item: any) => ({ id: item.id, productId: item.productId, serviceId: item.serviceId, type: item.type, name: item.name, price: Number(item.price), quantity: item.quantity, discount: Number(item.discount), total: Number(item.total), image: item.product?.imageUrl ?? item.service?.imageUrl ?? null, sessions: item.service?.sessions ?? null })), payment: order.payment ? { ...order.payment, amount: Number(order.payment.amount) } : null }; }
}
