import { apiRequest } from "./client";
import type { Order, OrderStatus } from "@/types/order";
type ApiOrder = { id: string; userId: string; status: "PENDING" | "CONFIRMED" | "PROCESSING" | "COMPLETED" | "CANCELLED"; subtotal: number; discount: number; total: number; name: string; email: string; phone: string | null; address: string; city: string; state: string; country: string; postalCode: string; items: Array<{ id: string; productId: string | null; serviceId: string | null; type: "PRODUCT" | "SERVICE"; name: string; price: number; quantity: number; total: number; image: string | null; sessions: number | null }>; payment: { status: "PENDING" | "PAID" | "REFUNDED" | "FAILED" | "CANCELLED"; currency: string } | null; createdAt: string };
type ListResponse = { success: boolean; data: ApiOrder[] };
type OneResponse = { success: boolean; data: ApiOrder };
const statusMap: Record<ApiOrder["status"], OrderStatus> = { PENDING: "New", CONFIRMED: "Confirmed", PROCESSING: "Processing", COMPLETED: "Completed", CANCELLED: "Cancelled" };
const reverseStatus: Record<OrderStatus, ApiOrder["status"]> = { New: "PENDING", Confirmed: "CONFIRMED", Processing: "PROCESSING", Shipped: "CONFIRMED", Delivered: "COMPLETED", Completed: "COMPLETED", Cancelled: "CANCELLED", Refunded: "CANCELLED" };
function mapOrder(item: ApiOrder): Order { const hasProduct = item.items.some((orderItem) => orderItem.type === "PRODUCT"); const hasService = item.items.some((orderItem) => orderItem.type === "SERVICE"); return { id: item.id, type: hasProduct && hasService ? "Mixed" : hasService ? "Service" : "Product", customer: { name: item.name, email: item.email, phone: item.phone ?? undefined, address: [item.address, item.city, item.state, item.country, item.postalCode].filter(Boolean).join(", ") }, items: item.items.map((orderItem) => ({ name: orderItem.name, quantity: orderItem.quantity, price: orderItem.price, total: orderItem.total, type: orderItem.type, image: orderItem.image ?? undefined, sessions: orderItem.sessions ?? undefined })), subtotal: item.subtotal, discount: item.discount, totalAmount: item.total, displayTotal: `${item.payment?.currency ?? "USD"} ${item.total.toFixed(2)}`, currency: item.payment?.currency ?? "USD", paymentStatus: item.payment?.status === "PAID" ? "Paid" : item.payment?.status === "REFUNDED" ? "Refunded" : "Pending", status: statusMap[item.status], createdAt: item.createdAt }; }
export async function getOrders(query: { status?: string; search?: string } = {}) { const params = new URLSearchParams(); if (query.status) params.set("status", query.status); if (query.search) params.set("search", query.search); return (await apiRequest<ListResponse>(`/orders${params.size ? `?${params.toString()}` : ""}`)).data.map(mapOrder); }
export async function getOrder(id: string) { return mapOrder((await apiRequest<OneResponse>(`/orders/${id}`)).data); }
export async function getMyOrders() { return (await apiRequest<ListResponse>("/orders/my-orders")).data.map(mapOrder); }
export async function getMyOrder(id: string) { return mapOrder((await apiRequest<OneResponse>(`/orders/my-orders/${encodeURIComponent(id)}`)).data); }
export async function updateOrderStatus(id: string, status: OrderStatus) { return mapOrder((await apiRequest<OneResponse>(`/orders/${id}/status`, { method: "PATCH", body: JSON.stringify({ status: reverseStatus[status] }) })).data); }
export async function createOrder(data: { name: string; email: string; phone?: string; address: string; city: string; state: string; country: string; postalCode: string; currency?: string; items: Array<{ type: "PRODUCT" | "SERVICE"; productId?: string; serviceId?: string; quantity: number }> }) { return (await apiRequest<OneResponse>("/orders", { method: "POST", body: JSON.stringify(data) })).data; }
