import { apiRequest } from "./client";
import type { Order, OrderStatus } from "@/types/order";
type ApiOrder = { id: string; userId: string; status: "NEW" | "PENDING" | "CONFIRMED" | "PROCESSING" | "SHIPPED" | "OUT_FOR_DELIVERY" | "DELIVERED" | "COMPLETED" | "CANCELLED" | "REFUNDED"; subtotal: number; discount: number; shippingCharge?: number; total: number; name: string; email: string; phone: string | null; address: string; city: string; state: string; country: string; postalCode: string; items: Array<{ id: string; productId: string | null; serviceId: string | null; type: "PRODUCT" | "SERVICE"; name: string; price: number; quantity: number; discount?: number; total: number; image: string | null; sessions: number | null }>; payment: { id?: string; status: "PENDING" | "PAID" | "REFUNDED" | "FAILED" | "CANCELLED"; currency: string; transactionId?: string | null; paymentMethod?: string | null; paidAt?: string | null } | null; createdAt: string; updatedAt?: string };
type ListResponse = { success: boolean; data: ApiOrder[] };
type OneResponse = { success: boolean; data: ApiOrder };
const statusMap: Record<ApiOrder["status"], OrderStatus> = { NEW: "New", PENDING: "New", CONFIRMED: "Confirmed", PROCESSING: "Processing", SHIPPED: "Shipped", OUT_FOR_DELIVERY: "Out for Delivery", DELIVERED: "Delivered", COMPLETED: "Delivered", CANCELLED: "Cancelled", REFUNDED: "Refunded" };
const reverseStatus: Record<OrderStatus, ApiOrder["status"]> = { New: "NEW", Confirmed: "CONFIRMED", Processing: "PROCESSING", Shipped: "SHIPPED", "Out for Delivery": "OUT_FOR_DELIVERY", Delivered: "DELIVERED", Cancelled: "CANCELLED", Refunded: "REFUNDED" };
function mapOrder(item: ApiOrder): Order { const hasProduct = item.items.some((orderItem) => orderItem.type === "PRODUCT"); const hasService = item.items.some((orderItem) => orderItem.type === "SERVICE"); return { id: item.id, type: hasProduct && hasService ? "Mixed" : hasService ? "Service" : "Product", customer: { name: item.name, email: item.email, phone: item.phone ?? undefined, address: [item.address, item.city, item.state, item.country, item.postalCode].filter(Boolean).join(", ") }, items: item.items.map((orderItem) => ({ name: orderItem.name, quantity: orderItem.quantity, price: orderItem.price, total: orderItem.total, type: orderItem.type, image: orderItem.image ?? undefined, sessions: orderItem.sessions ?? undefined })), subtotal: item.subtotal, discount: item.discount, shippingCharge: item.shippingCharge ?? 0, totalAmount: item.total, displayTotal: `USD ${item.total.toFixed(2)}`, currency: item.payment?.currency ?? "USD", paymentStatus: item.payment?.status === "PAID" ? "Paid" : item.payment?.status === "REFUNDED" ? "Refunded" : item.payment?.status === "FAILED" ? "Failed" : "Pending", status: statusMap[item.status], createdAt: item.createdAt, updatedAt: item.updatedAt }; }
export type AdminOrdersResult = { items: Order[]; pagination: { page: number; limit: number; total: number; totalPages: number } };
export async function getOrders(query: { page?: number; limit?: number; status?: string; search?: string; sort?: string } = {}) { const params = new URLSearchParams(); Object.entries(query).forEach(([key, value]) => { if (value !== undefined && value !== "") params.set(key, String(value)); }); const response = await apiRequest<{ success: boolean; data: { items: ApiOrder[]; pagination: AdminOrdersResult["pagination"] } }>(`/orders${params.size ? `?${params.toString()}` : ""}`); return { items: response.data.items.map(mapOrder), pagination: response.data.pagination }; }
export async function getOrder(id: string) { return mapOrder((await apiRequest<OneResponse>(`/orders/${id}`)).data); }
export async function getMyOrders() { return (await apiRequest<ListResponse>("/orders/my-orders")).data.map(mapOrder); }
export async function getMyOrder(id: string) { return mapOrder((await apiRequest<OneResponse>(`/orders/my-orders/${encodeURIComponent(id)}`)).data); }
export async function updateOrderStatus(id: string, status: OrderStatus, reason?: string) { return mapOrder((await apiRequest<OneResponse>(`/orders/${id}/status`, { method: "PATCH", body: JSON.stringify({ status: reverseStatus[status], reason }) })).data); }
export async function getAdminOrderStats() { return (await apiRequest<{ success: boolean; data: { counts: Record<string, number>; totalValue: number; totalShipping: number; totalOrders: number } }>("/orders/admin/stats")).data; }
export async function getAdminOrderHistory(id: string) { return (await apiRequest<{ success: boolean; data: Array<{ id: string; previousStatus: string | null; newStatus: string; changedBy: string | null; actorType: string; reason: string | null; changedAt: string }> }>(`/orders/${encodeURIComponent(id)}/history`)).data; }
export async function createOrder(data: { name: string; email: string; phone?: string; address: string; city: string; state: string; country: string; postalCode: string; currency?: string; items: Array<{ type: "PRODUCT" | "SERVICE"; productId?: string; serviceId?: string; quantity: number }> }) { return (await apiRequest<OneResponse>("/orders", { method: "POST", body: JSON.stringify(data) })).data; }
