import { apiRequest } from "./client";
import type { Order, OrderStatus, OrderStatusHistory } from "@/types/order";
type ApiOrder = { id: string; userId: string; status: string; subtotal: number; discount: number; shippingCharge?: number; total: number; couponId?: string | null; couponCode?: string | null; couponDiscountType?: "PERCENTAGE" | null; couponDiscountValue?: number | null; couponDiscountAmount?: number | null; name: string; email: string; phone: string | null; address: string; city: string; state: string; country: string; postalCode: string; items: Array<{ id: string; productId: string | null; serviceId: string | null; type: "PRODUCT" | "SERVICE"; name: string; price: number; quantity: number; discount?: number; total: number; image: string | null; sessions: number | null }>; payment: { id?: string; status: "PENDING" | "PAID" | "REFUNDED" | "FAILED" | "CANCELLED"; currency: string; transactionId?: string | null; paymentMethod?: string | null; paidAt?: string | null } | null; createdAt: string; updatedAt?: string };
type ListResponse = { success: boolean; data: ApiOrder[] };
type OneResponse = { success: boolean; data: ApiOrder };
function mapOrder(item: ApiOrder): Order { const hasProduct = item.items.some((orderItem) => orderItem.type === "PRODUCT"); const hasService = item.items.some((orderItem) => orderItem.type === "SERVICE"); return { id: item.id, type: hasProduct && hasService ? "Mixed" : hasService ? "Service" : "Product", customer: { name: item.name, email: item.email, phone: item.phone ?? undefined, address: [item.address, item.city, item.state, item.country, item.postalCode].filter(Boolean).join(", ") }, items: item.items.map((orderItem) => ({ name: orderItem.name, quantity: orderItem.quantity, price: Number(orderItem.price), total: Number(orderItem.total), type: orderItem.type, image: orderItem.image ?? undefined, sessions: orderItem.sessions ?? undefined })), subtotal: Number(item.subtotal), discount: Number(item.discount), shippingCharge: Number(item.shippingCharge ?? 0), totalAmount: Number(item.total), couponCode: item.couponCode ?? undefined, couponDiscountType: item.couponDiscountType ?? undefined, couponDiscountValue: item.couponDiscountValue === null || item.couponDiscountValue === undefined ? undefined : Number(item.couponDiscountValue), couponDiscountAmount: item.couponDiscountAmount === null || item.couponDiscountAmount === undefined ? undefined : Number(item.couponDiscountAmount), displayTotal: `USD ${Number(item.total).toFixed(2)}`, currency: item.payment?.currency ?? "USD", paymentStatus: item.payment?.status === "PAID" ? "Paid" : item.payment?.status === "REFUNDED" ? "Refunded" : item.payment?.status === "FAILED" ? "Failed" : "Pending", status: item.status, createdAt: item.createdAt, updatedAt: item.updatedAt }; }
export type AdminOrdersResult = { items: Order[]; pagination: { page: number; limit: number; total: number; totalPages: number } };
export async function getOrders(query: { page?: number; limit?: number; status?: string; other?: boolean; search?: string; sort?: string } = {}) { const params = new URLSearchParams(); Object.entries(query).forEach(([key, value]) => { if (value !== undefined && value !== "") params.set(key, String(value)); }); const response = await apiRequest<{ success: boolean; data: { items: ApiOrder[]; pagination: AdminOrdersResult["pagination"] } }>(`/orders${params.size ? `?${params.toString()}` : ""}`); return { items: response.data.items.map(mapOrder), pagination: response.data.pagination }; }
export async function getOrder(id: string) { return mapOrder((await apiRequest<OneResponse>(`/orders/${id}`)).data); }
export async function getMyOrders() { return (await apiRequest<ListResponse>("/orders/my-orders")).data.map(mapOrder); }
export async function getMyOrder(id: string) { return mapOrder((await apiRequest<OneResponse>(`/orders/my-orders/${encodeURIComponent(id)}`)).data); }
export async function updateOrderStatus(id: string, status: OrderStatus) { return mapOrder((await apiRequest<OneResponse>(`/orders/${id}/status`, { method: "PATCH", body: JSON.stringify({ status: status.trim() }) })).data); }
export async function getAdminOrderStats() { return (await apiRequest<{ success: boolean; data: { counts: Record<string, number>; totalValue: number; totalShipping: number; totalOrders: number } }>("/orders/admin/stats")).data; }
export async function getOrderStatusHistory(id: string) { return (await apiRequest<{ success: boolean; data: OrderStatusHistory[] }>(`/orders/${encodeURIComponent(id)}/history`)).data; }
export const getAdminOrderHistory = getOrderStatusHistory;
export async function createOrder(data: { name: string; email: string; phone?: string; address: string; city: string; state: string; country: string; postalCode: string; currency?: string; couponCode?: string; items: Array<{ type: "PRODUCT" | "SERVICE"; productId?: string; serviceId?: string; quantity: number }> }) { return (await apiRequest<OneResponse>("/orders", { method: "POST", body: JSON.stringify(data) })).data; }
