import { apiRequest } from "./client";
export type BookingSession = { date: string; time: string };
export type ServiceBookingInput = { serviceId: string; sessions: BookingSession[]; name?: string; email?: string; phone?: string; address: string; city: string; state: string; country: string; postalCode: string };
export async function createServiceBooking(data: ServiceBookingInput) { return (await apiRequest<{ success: boolean; data: { id: string; orderId: string; quantity: number; pricePerSession: number; totalAmount: number; status: string; sessions: Array<{ id: string; scheduledAt: string }> } }>("/service-bookings", { method: "POST", body: JSON.stringify(data) })).data; }
export type ServiceBooking = { id: string; orderId: string; service: { name: string; imageUrl?: string | null }; trainer: { id: string; name: string; profileImageUrl?: string | null }; quantity: number; pricePerSession: number; totalAmount: number; status: string; paymentStatus: string | null; address: { address: string; city: string; state: string; country: string; postalCode: string }; sessions: Array<{ id: string; scheduledAt: string; status: string }> };
export async function getServiceBookings() { return (await apiRequest<{ success: boolean; data: ServiceBooking[] }>("/service-bookings")).data; }

export type AdminServiceBookingStatus = "PENDING_PAYMENT" | "SCHEDULED" | "COMPLETED" | "CANCELLED";
export type AdminServiceBooking = { id: string; orderId: string; service: { id: string; name: string; description?: string | null; price: number; imageUrl?: string | null } | null; trainer: { id: string; name: string; email?: string; phone?: string | null; profileImageUrl?: string | null; specialty?: string | null; experience?: string | null }; customer: { id: string; name: string; email: string; phone?: string | null; address?: { address: string; city: string; state: string; country: string; postalCode: string } | null }; quantity: number; pricePerSession: number; totalAmount: number; status: AdminServiceBookingStatus; payment: { id: string; status: string; amount: number; currency: string; paymentMethod?: string | null; paidAt?: string | null } | null; sessions: Array<{ id: string; scheduledAt: string; status: string }>; createdAt: string; updatedAt: string };
export type ServiceBookingStats = { total: number; pending: number; scheduled: number; upcoming: number; completed: number; cancelled: number; revenue: number };
type AdminBookingResponse = { success: boolean; data: { items: AdminServiceBooking[]; pagination: { page: number; limit: number; total: number; totalPages: number } } };
export async function getAdminServiceBookings(query: { page?: number; limit?: number; search?: string; status?: string; paymentStatus?: string; serviceId?: string; trainerId?: string; date?: string; upcoming?: boolean } = {}) { const params = new URLSearchParams(); Object.entries(query).forEach(([key, value]) => { if (value !== undefined && value !== "") params.set(key, String(value)); }); return (await apiRequest<AdminBookingResponse>(`/service-bookings/admin${params.size ? `?${params.toString()}` : ""}`)).data; }
export async function getAdminServiceBookingStats() { return (await apiRequest<{ success: boolean; data: ServiceBookingStats }>("/service-bookings/admin/stats")).data; }
export async function getAdminServiceBooking(id: string) { return (await apiRequest<{ success: boolean; data: AdminServiceBooking }>(`/service-bookings/admin/${encodeURIComponent(id)}`)).data; }
export async function updateAdminServiceBookingStatus(id: string, status: AdminServiceBookingStatus) { return (await apiRequest<{ success: boolean; data: AdminServiceBooking }>(`/service-bookings/admin/${encodeURIComponent(id)}/status`, { method: "PATCH", body: JSON.stringify({ status }) })).data; }
