"use client";

import { useCallback, useEffect, useState } from "react";
import { getTrainerBookings, type TrainerBooking } from "@/api/trainer-bookings.api";
import { Button } from "@/components/ui/button";
import { TrainerBookingCard } from "./trainer-booking-card";
import { TrainerBookingSkeleton, TrainerEmptyState, TrainerErrorState } from "./trainer-states";

export function TrainerBookingsPage() {
  const [bookings, setBookings] = useState<TrainerBooking[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [refreshing, setRefreshing] = useState(false); const [filter, setFilter] = useState<"all" | "pending">("pending");
  const load = useCallback(async (manual = false) => { if (manual) setRefreshing(true); else setLoading(true); setError(""); try { setBookings(await getTrainerBookings()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load bookings."); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = filter === "pending" ? bookings.filter((booking) => booking.status === "PENDING") : bookings.filter((booking) => booking.status !== "COMPLETED" && booking.status !== "CANCELLED");
  return <div><header className="flex flex-col justify-between gap-5 border-b border-black/10 pb-8 sm:flex-row sm:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-brand-purple">Trainer workspace</p><h1 className="mt-3 text-4xl sm:text-5xl">Bookings</h1><p className="mt-3 text-sm text-brand-gray">Review new requests and prepare for the sessions assigned to you.</p></div><Button className="w-full sm:w-auto" disabled={loading || refreshing} onClick={() => void load(true)} type="button">{refreshing ? "Refreshing…" : "Refresh"}</Button></header>{error ? <div className="mt-8"><TrainerErrorState message={error} onRetry={() => void load()} /></div> : loading ? <div className="mt-8"><TrainerBookingSkeleton /></div> : <><div className="mt-8 flex flex-wrap gap-2" role="tablist" aria-label="Booking filters"><button aria-selected={filter === "pending"} className={`rounded-full px-5 py-3 text-xs font-semibold uppercase tracking-[0.12em] ${filter === "pending" ? "bg-brand-purple text-white" : "bg-white text-brand-gray"}`} onClick={() => setFilter("pending")} role="tab" type="button">New bookings ({bookings.filter((booking) => booking.status === "PENDING").length})</button><button aria-selected={filter === "all"} className={`rounded-full px-5 py-3 text-xs font-semibold uppercase tracking-[0.12em] ${filter === "all" ? "bg-brand-purple text-white" : "bg-white text-brand-gray"}`} onClick={() => setFilter("all")} role="tab" type="button">Active schedule</button></div><section aria-label="Trainer bookings" className="mt-6 space-y-4">{visible.length ? visible.map((booking) => <TrainerBookingCard booking={booking} key={booking.id} />) : <TrainerEmptyState description={filter === "pending" ? "New paid bookings assigned to you will appear here." : "There are no active bookings on your schedule."} title={filter === "pending" ? "No new bookings" : "No active bookings"} />}</section></>}</div>;
}
