import { ConflictException, Injectable, Logger, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service.js';
import { CloudinaryService } from '../../cloudinary/cloudinary.service.js';
import type { CreateServiceDto } from './dto/create-service.dto.js';
import type { UpdateServiceAvailabilityDto } from './dto/update-service-availability.dto.js';
import type { UpdateServiceDto } from './dto/update-service.dto.js';
const serviceSelect = { id: true, name: true, slug: true, description: true, price: true, sessions: true, status: true, imageUrl: true, imagePublicId: true, createdAt: true, updatedAt: true } as const;
const slugify = (value: string) => value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 120) || 'service';
const code = (error: unknown) => error && typeof error === 'object' && 'code' in error ? error.code : undefined;
@Injectable()
export class ServicesService {
  private readonly logger = new Logger(ServicesService.name);
  constructor(private readonly prisma: PrismaService, private readonly cloudinary: CloudinaryService) {}
  async findAll(query: { search?: string; status?: string }) { const search = query.search?.trim(); const rows = await this.prisma.service.findMany({ where: { ...(search ? { OR: [{ name: { contains: search, mode: 'insensitive' } }, { description: { contains: search, mode: 'insensitive' } }] } : {}), ...(query.status === 'all' ? {} : { status: query.status === 'inactive' ? 'INACTIVE' : 'ACTIVE' }) }, orderBy: { createdAt: 'desc' }, select: serviceSelect }); return rows.map((row) => this.present(row)); }
  async findOne(id: string) { const row = await this.prisma.service.findUnique({ where: { id }, select: serviceSelect }); if (!row) throw new NotFoundException('Service not found'); return this.present(row); }
  async findBySlug(slug: string) { const row = await this.prisma.service.findUnique({ where: { slug }, select: serviceSelect }); if (!row) throw new NotFoundException('Service not found'); return this.present(row); }
  async create(dto: CreateServiceDto, file?: Express.Multer.File) { const uploaded = file ? await this.cloudinary.uploadImage(file, 'services') : undefined; try { const row = await this.prisma.service.create({ data: { name: dto.name.trim(), slug: slugify(dto.name), description: dto.description?.trim() || null, price: dto.price, sessions: dto.sessions, status: dto.status === false ? 'INACTIVE' : 'ACTIVE', imageUrl: uploaded?.secure_url ?? dto.imageUrl?.trim() ?? null, imagePublicId: uploaded?.public_id ?? null }, select: serviceSelect }); return this.present(row); } catch (error) { if (uploaded) await this.cleanup(uploaded.public_id); this.throwDatabaseError(error); } }
  async update(id: string, dto: UpdateServiceDto, file?: Express.Multer.File) { const current = await this.prisma.service.findUnique({ where: { id }, select: serviceSelect }); if (!current) throw new NotFoundException('Service not found'); const uploaded = file ? await this.cloudinary.uploadImage(file, 'services') : undefined; const data: Record<string, unknown> = {}; if (dto.name !== undefined) { data.name = dto.name.trim(); data.slug = slugify(dto.name); } if (dto.description !== undefined) data.description = dto.description.trim() || null; if (dto.price !== undefined) data.price = dto.price; if (dto.sessions !== undefined) data.sessions = dto.sessions; if (dto.status !== undefined) data.status = dto.status ? 'ACTIVE' : 'INACTIVE'; if (uploaded) { data.imageUrl = uploaded.secure_url; data.imagePublicId = uploaded.public_id; } else if (dto.removeImage) { data.imageUrl = null; data.imagePublicId = null; } else if (dto.imageUrl !== undefined) { data.imageUrl = dto.imageUrl.trim(); data.imagePublicId = null; } try { const row = await this.prisma.service.update({ where: { id }, data, select: serviceSelect }); if ((uploaded || dto.removeImage || dto.imageUrl !== undefined) && current.imagePublicId && current.imagePublicId !== uploaded?.public_id) await this.cleanup(current.imagePublicId); return this.present(row); } catch (error) { if (uploaded) await this.cleanup(uploaded.public_id); this.throwDatabaseError(error); } }
  updateAvailability(id: string, dto: UpdateServiceAvailabilityDto) { return this.update(id, { status: dto.available }); }
  async remove(id: string) { const current = await this.prisma.service.findUnique({ where: { id }, select: serviceSelect }); if (!current) throw new NotFoundException('Service not found'); try { await this.prisma.service.delete({ where: { id } }); if (current.imagePublicId) await this.cleanup(current.imagePublicId); return { id }; } catch (error) { if (code(error) === 'P2003') throw new ConflictException('Service cannot be deleted because it is referenced by an order'); throw error; } }
  private async cleanup(publicId: string) { try { await this.cloudinary.deleteImage(publicId); } catch (error) { this.logger.error(`Cloudinary cleanup failed for ${publicId}`, error); } }
  private throwDatabaseError(error: unknown): never { if (code(error) === 'P2002') throw new ConflictException('A service with this name already exists'); throw error; }
  private present(row: any) { return { id: row.id, name: row.name, slug: row.slug, description: row.description, price: Number(row.price), sessions: row.sessions, imageUrl: row.imageUrl ?? null, imagePublicId: row.imagePublicId ?? null, available: row.status === 'ACTIVE', status: row.status === 'ACTIVE' ? 'Active' : 'Inactive', createdAt: row.createdAt, updatedAt: row.updatedAt }; }
}
