"use client";
import { useEffect, useMemo, useState } from "react";
import { getOrders, updateOrderStatus } from "@/api/orders.api";
import { CustomerPagination } from "@/components/admin/customers/customer-pagination";
import { CustomerSearch } from "@/components/admin/customers/customer-search";
import { Container } from "@/components/ui/container";
import type { Order, OrderStatus, OrderType } from "@/types/order";
import { OrderDetailsDialog } from "./order-details-dialog";
import { OrderTable } from "./order-table";
import { orderStatuses } from "./order-status-selector";
type Props = { title: string; description: string; filter?: OrderStatus; statusControls?: boolean; allowStatusFilter?: boolean };
const PAGE_SIZE = 10;
export function OrdersListPage({ title, description, filter, statusControls = false, allowStatusFilter = false }: Props) {
  const [orders, setOrders] = useState<Order[]>([]); const [query, setQuery] = useState(""); const [typeFilter, setTypeFilter] = useState<OrderType | "All">("All"); const [statusFilter, setStatusFilter] = useState<OrderStatus | "All">(filter ?? "All"); const [selectedOrder, setSelectedOrder] = useState<Order>(); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [feedback, setFeedback] = useState("");
  useEffect(() => { getOrders().then(setOrders).catch((e: unknown) => setError(e instanceof Error ? e.message : "Unable to load orders.")).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => orders.filter((order) => (!filter || order.status === filter) && (statusFilter === "All" || order.status === statusFilter) && (typeFilter === "All" || order.type === typeFilter) && (!query.trim() || `${order.id} ${order.customer.name} ${order.customer.email} ${order.items.map((item) => item.name).join(" ")}`.toLowerCase().includes(query.trim().toLowerCase()))), [orders, filter, statusFilter, typeFilter, query]); const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  async function changeStatus(id: string, status: OrderStatus) { try { const saved = await updateOrderStatus(id, status); setOrders((current) => current.map((order) => order.id === saved.id ? saved : order)); setSelectedOrder((current) => current?.id === saved.id ? saved : current); setFeedback("Order status updated successfully."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update order status."); } }
  return <Container className="py-10 sm:py-12 lg:py-16"><div className="border-b border-black/10 pb-8"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-brand-purple">Sattva administration</p><h1 className="mt-3 text-4xl sm:text-5xl">{title}</h1><p className="mt-3 text-sm text-brand-gray">{description}</p></div>{error && <p className="mt-6 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{error}</p>}{feedback && <p className="mt-5 text-sm text-green-700">{feedback}</p>}<div className="mt-8 flex flex-col gap-4 sm:flex-row sm:items-center"><CustomerSearch onChange={setQuery} value={query} /><select aria-label="Filter orders by type" className="h-12 rounded-md border border-black/10 bg-white px-4 text-sm text-brand-dark outline-none focus:border-brand-purple" onChange={(event) => { setTypeFilter(event.target.value as OrderType | "All"); setPage(1); }} value={typeFilter}><option value="All">All types</option><option value="Product">Products</option><option value="Service">Services</option><option value="Mixed">Mixed</option></select>{allowStatusFilter && <select aria-label="Filter orders by status" className="h-12 rounded-md border border-black/10 bg-white px-4 text-sm text-brand-dark outline-none focus:border-brand-purple" onChange={(event) => { setStatusFilter(event.target.value as OrderStatus | "All"); setPage(1); }} value={statusFilter}><option value="All">All statuses</option>{orderStatuses.map((status) => <option key={status} value={status}>{status}</option>)}</select>}<span className="whitespace-nowrap text-sm text-brand-gray">{filtered.length} orders</span></div><section aria-label={`${title} list`} className="mt-6 overflow-hidden bg-white shadow-sm">{loading ? <div className="px-6 py-20 text-center text-sm text-brand-gray">Loading orders…</div> : <><OrderTable onStatusChange={changeStatus} onView={setSelectedOrder} orders={visible} statusControls={statusControls} /><CustomerPagination currentPage={Math.min(page, totalPages)} onPageChange={setPage} totalPages={totalPages} /></>}</section>{selectedOrder && <OrderDetailsDialog onClose={() => setSelectedOrder(undefined)} order={selectedOrder} />}</Container>;
}
