"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { getAdminOrderStats } from "@/api/orders.api";
import { Container } from "@/components/ui/container";

const cards = [["NEW", "New", "/admin/orders/new"], ["CONFIRMED", "Confirmed", "/admin/orders/confirmed"], ["PROCESSING", "Processing", "/admin/orders/processing"], ["SHIPPED", "Shipped", "/admin/orders/shipped"], ["OUT_FOR_DELIVERY", "Out for Delivery", "/admin/orders/out-for-delivery"], ["DELIVERED", "Delivered", "/admin/orders/delivered"], ["CANCELLED", "Cancelled", "/admin/orders/cancelled"], ["REFUNDED", "Refunded", "/admin/orders/refunded"]] as const;
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);
export function OrdersOverviewPage() { const [stats, setStats] = useState<Awaited<ReturnType<typeof getAdminOrderStats>>>(); const [error, setError] = useState(""); useEffect(() => { getAdminOrderStats().then(setStats).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load order metrics.")); }, []); return <Container className="py-10 sm:py-12 lg:py-16"><header className="flex flex-col justify-between gap-5 border-b border-black/10 pb-8 sm:flex-row sm:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-brand-purple">Product order operations</p><h1 className="mt-3 text-4xl sm:text-5xl">Orders Overview</h1><p className="mt-3 text-sm text-brand-gray">Move product orders through their validated lifecycle. Service bookings are managed separately.</p></div><Link className="inline-flex min-h-11 items-center justify-center border border-brand-purple px-5 text-[10px] font-semibold uppercase tracking-[0.14em] text-brand-purple" href="/admin/orders/all">All orders / history</Link></header>{error && <p className="mt-6 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{!stats ? <div className="mt-8 bg-white px-6 py-20 text-center text-sm text-brand-gray">Loading order metrics…</div> : <><section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{cards.map(([key, label, href]) => <Link className="bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md" href={href} key={key}><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-brand-gray">{label}</p><p className="mt-3 font-serif text-3xl">{stats.counts[key] ?? 0}</p><p className="mt-2 text-[10px] font-semibold uppercase tracking-[0.1em] text-brand-purple">View orders →</p></Link>)}</section><section className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="Total order value" value={money(stats.totalValue)} /><Metric label="Total shipping charges" value={money(stats.totalShipping)} /><Metric label="Total orders" value={String(stats.totalOrders)} /></section></>}</Container>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="bg-brand-purple p-6 text-white shadow-sm"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-white/70">{label}</p><p className="mt-3 font-serif text-3xl">{value}</p></div>; }
