import type { Order, OrderStatus } from "@/types/order";

import { OrderStatusBadge } from "./order-status-badge";
import { OrderStatusSelector } from "./order-status-selector";

type OrderTableProps = { orders: Order[]; statusControls?: boolean; onStatusChange?: (id: string, status: OrderStatus) => void; onView?: (order: Order) => void };
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const date = (value?: string) => value ? new Intl.DateTimeFormat("en-US", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "—";

export function OrderTable({ orders, statusControls = false, onStatusChange, onView }: OrderTableProps) {
  if (!orders.length) return <div className="px-6 py-20 text-center"><p className="font-serif text-2xl">No orders found</p><p className="mt-2 text-sm text-brand-gray">Try adjusting your search or filters.</p></div>;
  return <div className="overflow-x-auto"><table className="w-full min-w-[1200px] border-collapse text-left"><thead><tr className="border-b border-black/10 text-[10px] font-semibold uppercase tracking-[0.16em] text-brand-gray"><th className="px-6 py-4">Order</th><th className="px-6 py-4">Type</th><th className="px-6 py-4">Items</th><th className="px-6 py-4">Customer</th><th className="px-6 py-4">Date</th><th className="px-6 py-4">Qty</th><th className="px-6 py-4">Total</th><th className="px-6 py-4">Payment</th><th className="px-6 py-4">Status</th>{statusControls && <th className="px-6 py-4">Update</th>}</tr></thead><tbody>{orders.map((order) => <tr className="cursor-pointer border-b border-black/5 transition-colors last:border-0 hover:bg-brand-light-gray/70" key={order.id} onClick={() => onView?.(order)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") onView?.(order); }} role="button" tabIndex={0}><td className="px-6 py-5 text-sm font-semibold">{order.id}</td><td className="px-6 py-5"><span className="rounded-full bg-brand-purple/10 px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.1em] text-brand-purple">{order.type}</span></td><td className="max-w-[220px] px-6 py-5 text-sm text-brand-dark">{order.items.map((item) => item.name).join(", ")}</td><td className="max-w-[220px] px-6 py-5"><p className="truncate text-sm font-semibold">{order.customer.name}</p><p className="truncate text-xs text-brand-gray">{order.customer.email}</p></td><td className="whitespace-nowrap px-6 py-5 text-sm text-brand-gray">{date(order.createdAt)}</td><td className="px-6 py-5 text-sm text-brand-gray">{order.items.reduce((sum, item) => sum + item.quantity, 0)}</td><td className="whitespace-nowrap px-6 py-5 text-sm font-semibold">{order.displayTotal || money.format(order.totalAmount)}</td><td className="px-6 py-5 text-sm text-brand-gray">{order.paymentStatus}</td><td className="px-6 py-5"><OrderStatusBadge status={order.status} /></td>{statusControls && <td className="px-6 py-5" onClick={(event) => event.stopPropagation()}><OrderStatusSelector onChange={(status) => onStatusChange?.(order.id, status)} value={order.status} /></td>}</tr>)}</tbody></table></div>;
}
